const {chromium,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
const fs=require('node:fs');
const checks=[],audits=[];
const nav=async(p,path)=>{await p.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);await p.waitForTimeout(400)};
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const p=await c.newPage();p.setDefaultTimeout(12000);try{await c.request.post('http://127.0.0.1:5177/demo-api/rpc',{headers:{Origin:'http://127.0.0.1:5177'},data:{method:'resetDemo',args:[]}});await p.goto('http://127.0.0.1:5177/admin',{waitUntil:'networkidle'});await p.getByRole('button',{name:/デモ管理画面に入る/}).click();
 const confirm=async()=>{await p.getByRole('dialog').getByLabel(/^変更理由/).fill('公開前のデモ検証');await p.getByRole('dialog').getByRole('button',{name:'変更を確定する'}).click();await expect(p.getByRole('dialog')).toHaveCount(0)};
 await p.getByRole('button',{name:'記事',exact:true}).click();await p.getByText('新しい記事を作成する',{exact:true}).click();const article=p.locator('details[open]').last();await article.getByLabel(/^タイトル/).fill('公開管理の確認記事');await article.getByLabel(/^本文/).fill('デモの記事です。');await article.getByLabel('公開する',{exact:true}).check();await article.getByRole('button',{name:'保存内容を確認する'}).click();await confirm();await nav(p,'/news');await expect(p.getByRole('heading',{name:'公開管理の確認記事',exact:true})).toBeVisible();await p.getByRole('link',{name:/公開管理の確認記事/}).click();await expect(p.getByText('デモの記事です。',{exact:true})).toBeVisible();checks.push('article creation/publication reflected in public list and detail');
 await p.goto('http://127.0.0.1:5177/admin',{waitUntil:'networkidle'});await p.getByRole('button',{name:'運営設定',exact:true}).click();const shipping=p.locator('form.admin-record').first();await shipping.getByLabel(/^基本送料/).fill('880');await shipping.getByRole('button',{name:'保存を確認する'}).click();await confirm();await p.goto('http://127.0.0.1:5179/products/c01',{waitUntil:'networkidle'});await expect(p.locator('.shipping-info')).toContainText('880');checks.push('shipping configuration reflected in product delivery information');
 await p.goto('http://127.0.0.1:5177/admin',{waitUntil:'networkidle'});await p.getByRole('button',{name:'商品',exact:true}).click();await p.getByText('化粧品の商品を新規作成',{exact:true}).click();const product=p.locator('details[open]').first();await product.getByLabel(/^商品名/).fill('新商品の確認');await product.getByLabel(/^税込価格/).fill('1200');await product.getByLabel(/^内容量/).fill('100mL');await product.getByLabel(/^商品説明/).fill('正式販売前のサンプルです。');await product.getByRole('button',{name:'保存内容を確認する'}).click();await confirm();await expect(p.locator('.product-editor').filter({hasText:'新商品の確認'})).toContainText('￥1,200');checks.push('new product created stopped, with category and media fields');
 await p.getByRole('button',{name:'紹介制度',exact:true}).click();const ref=p.locator('form').filter({has:p.getByLabel('新規紹介者名')});await ref.getByLabel('新規紹介者名').fill('追加紹介者');await ref.getByLabel('承認済み',{exact:true}).check();await ref.getByRole('button',{name:'登録・承認を確認する'}).click();await confirm();await expect(p.getByLabel(/^承認済み紹介者/)).toContainText('追加紹介者');checks.push('approved referrer becomes available for code issuance');
 await p.getByRole('button',{name:'会員',exact:true}).click();await p.getByText('デモ利用者 / demo@example.invalid',{exact:true}).click();await p.locator('details[open]').getByLabel(/^氏名/).fill('訂正したデモ利用者');await p.locator('details[open]').getByRole('button',{name:'訂正内容を確認する'}).click();await confirm();await expect(p.getByText('訂正したデモ利用者 / demo@example.invalid',{exact:true})).toBeVisible();await p.getByRole('button',{name:'変更履歴',exact:true}).click();await expect(p.getByText(/会員情報・紹介者訂正/)).toBeVisible();checks.push('member correction creates audit history');
 for(const tab of ['商品','記事','会員','紹介制度','運営設定','変更履歴']){await p.getByRole('button',{name:tab,exact:true}).click();await p.waitForTimeout(250);const result=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();audits.push({tab,violations:result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))});await p.screenshot({path:`qa/separation/admin-${tab}.png`,fullPage:true});await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),tab+' mobile overflow').toBe(false);await p.setViewportSize({width:1440,height:1000});}
 await nav(p,'/preview');await p.getByRole('radio',{name:'問い合わせ送信失敗',exact:true}).click();await nav(p,'/contact');await p.getByLabel(/^お名前/).fill('入力保持テスト');await p.getByLabel(/^メールアドレス/).fill('test@example.invalid');await p.getByLabel(/^件名/).fill('保持する件名');await p.getByLabel(/^お問い合わせ内容/).fill('保持する本文');await p.getByRole('checkbox').check();await p.getByRole('button',{name:/入力内容を確認する/}).click();await p.getByRole('button',{name:/この内容で送信する/}).click();await expect(p.getByRole('alert')).toBeVisible();await nav(p,'/preview');await p.getByRole('radio',{name:'通常の操作',exact:true}).click();await nav(p,'/contact');await expect(p.getByLabel(/^お問い合わせ内容/)).toHaveValue('保持する本文');await p.getByRole('button',{name:/入力内容を確認する/}).click();await p.getByRole('button',{name:/この内容で送信する/}).click();await expect(p.getByRole('heading',{name:'お問い合わせを受け付けました。'})).toBeVisible();checks.push('failed inquiry draft survives scenario navigation and succeeds on retry');
 fs.writeFileSync('qa/separation/admin-results.json',JSON.stringify({checks,audits},null,2));await b.close();console.log(JSON.stringify({checks:checks.length,violations:audits.reduce((s,a)=>s+a.violations.length,0)}));if(audits.some(a=>a.violations.length))process.exitCode=1;
 }catch(e){await p.screenshot({path:'qa/separation/admin-failure.png',fullPage:true});fs.writeFileSync('qa/separation/admin-results.json',JSON.stringify({checks,audits,failure:String(e)},null,2));await b.close();throw e;}})().catch(e=>{console.error(e);process.exit(1)});
