import { beforeEach,describe,it,expect } from 'vitest';
import { MockShopGateway } from '../src/gateway';
import { canonicalPath,safeNext } from '../src/router';
import type { Business,Scenario } from '../src/domain';
let g:MockShopGateway;
const member={name:'確認用会員',email:'member@example.invalid',phone:'000-0000-0000',address:'デモ住所',nickname:'にこ',age:'30代',password:'demopass',consent:true};
const address={name:'確認用会員',postal:'000-0000',address:'デモ住所',phone:'000-0000-0000'};
async function order(business:Business='cosmetics',method:'bank'|'paypay'='bank'){await g.changeCart(business,business==='cosmetics'?'c01':'a01',1);const q=await g.quoteCart(business);return g.createOrder({quoteId:q.id,address,paymentMethod:method,idempotencyKey:crypto.randomUUID(),consent:true});}
beforeEach(()=>{g=new MockShopGateway(0)});
describe('routes',()=>{
 it('moves old product paths and preserves ID, business, return path',()=>{expect(canonicalPath('/cosmetics/products/c01?business=cosmetics')).toBe('/shop/cosmetics/products/c01?business=cosmetics');expect(canonicalPath('/login?next=%2Fcheckout%3Fbusiness%3Dagriculture')).toBe('/shop/login?next=%2Fshop%2Fcheckout%3Fbusiness%3Dagriculture');expect(canonicalPath('/products/a01?business=agriculture')).toBe('/shop/agriculture/products/a01?business=agriculture');});
 it('rejects external login return destinations',()=>{for(const next of ['https://example.com','//example.com','/\\example.com','/shop/login'])expect(safeNext(next)).toBe('/shop/account');});
});
describe('members and products',()=>{
 it('allows anonymous products but rejects order creation and review text',async()=>{expect((await g.listProducts({business:'cosmetics'})).items.length).toBe(3);await expect(g.getReviews('c01')).rejects.toMatchObject({code:'UNAUTHENTICATED'});await expect(order()).rejects.toMatchObject({code:'UNAUTHENTICATED'});});
 it('requires complete membership information',async()=>{await expect(g.register({...member,nickname:''})).rejects.toMatchObject({code:'VALIDATION'});});
 it('invalid code can be removed to complete registration',async()=>{await expect(g.register({...member,referralCode:'invalid'})).rejects.toMatchObject({code:'REFERRAL_INVALID'});expect((await g.register(member)).referrerId).toBeUndefined();});
 it('maintains carts across logout and login',async()=>{await g.login('demo@example.invalid','demopass');await g.changeCart('cosmetics','c01',2);await g.changeCart('agriculture','a01',1);await g.logout();await g.login('demo@example.invalid','demopass');expect(g.getSnapshot().carts.cosmetics[0].quantity).toBe(2);expect(g.getSnapshot().carts.agriculture[0].quantity).toBe(1);});
 it('separates stopped, unavailable inventory, and inventory-untracked products',async()=>{await expect(g.changeCart('cosmetics','c03',1)).rejects.toMatchObject({code:'CONFLICT'});await expect(g.changeCart('agriculture','a03',1)).rejects.toMatchObject({code:'CONFLICT'});await g.changeCart('cosmetics','c02',50);await expect(g.changeCart('agriculture','c01',1)).rejects.toMatchObject({code:'VALIDATION'});await expect(g.changeCart('cosmetics','c01',9)).rejects.toMatchObject({code:'CONFLICT'});});
 it('agriculture only lists selling products, supports empty state and producer toggle',async()=>{await g.enterAdmin();await g.adminProduct('a01',{saleStatus:'stopped',producer:{visible:false,name:'x',description:'x'}},'確認');const list=await g.listProducts({business:'agriculture'});expect(list.items.map(p=>p.id)).not.toContain('a01');expect((await g.getProduct('agriculture','a01')).producer?.visible).toBe(false);g.setScenario('agriculture_empty');expect((await g.listProducts({business:'agriculture'})).items).toEqual([]);});
});
describe('quotes and orders',()=>{
 it('percentage discount only on eligible cosmetics, with separate shipping and carts',async()=>{await g.register({...member,referralCode:'DEMO10'});await g.changeCart('cosmetics','c01',2);await g.changeCart('agriculture','a01',1);const q=await g.quoteCart('cosmetics');expect(q).toMatchObject({subtotal:7700,discount:770,shipping:550,total:7480});const a=await g.quoteCart('agriculture');expect(a.discount).toBe(0);expect(a.shipping).toBe(770);await g.createOrder({quoteId:q.id,address,paymentMethod:'bank',idempotencyKey:'one',consent:true});expect(g.getSnapshot().carts.agriculture).toHaveLength(1);});
 it('fixed discount applies once per order',async()=>{await g.register({...member,referralCode:'DEMO500'});await g.changeCart('cosmetics','c01',2);await g.changeCart('cosmetics','c02',1);expect((await g.quoteCart('cosmetics')).discount).toBe(500);});
 it.each([['STOPPED','stopped'],['EXPIRED','period'],['USEDUP','limit'],['UNAPPROVED','unapproved'],['missing','not_found']] as const)('rejects %s referral condition',async(code,reason)=>{expect(await g.validateReferral(code)).toMatchObject({valid:false,reason});});
 it('rejects ineligible product and agriculture discounts',async()=>{expect(await g.validateReferral('DEMO10','cosmetics',['c03'])).toMatchObject({reason:'product'});expect(await g.validateReferral('DEMO10','agriculture',['a01'])).toMatchObject({reason:'business'});});
 it.each(['stock_changed','price_changed','sale_stopped'] as Scenario[])('blocks late %s without clearing cart',async scenario=>{await g.register(member);await g.changeCart('cosmetics','c01',1);const q=await g.quoteCart('cosmetics');g.setScenario(scenario);await expect(g.createOrder({quoteId:q.id,address,paymentMethod:'bank',idempotencyKey:'same',consent:true})).rejects.toMatchObject({code:'CONFLICT'});expect(g.getSnapshot().carts.cosmetics).toHaveLength(1);expect(await g.getOrders()).toEqual([]);});
 it('can reconfirm changed price',async()=>{await g.register(member);await g.changeCart('cosmetics','c01',1);let q=await g.quoteCart('cosmetics');g.setScenario('price_changed');const request={quoteId:q.id,address,paymentMethod:'bank' as const,idempotencyKey:'reconfirm',consent:true};await expect(g.createOrder(request)).rejects.toMatchObject({code:'CONFLICT'});q=await g.quoteCart('cosmetics');expect((await g.createOrder({...request,quoteId:q.id})).items[0].unitPrice).toBe(4150);});
 it('creates one order for concurrent duplicate confirmation',async()=>{await g.register(member);await g.changeCart('cosmetics','c01',1);const q=await g.quoteCart('cosmetics');const input={quoteId:q.id,address,paymentMethod:'bank' as const,idempotencyKey:'duplicate',consent:true};const [a,b]=await Promise.all([g.createOrder(input),g.createOrder(input)]);expect(a.id).toBe(b.id);expect(await g.getOrders()).toHaveLength(1);expect((await g.getProduct('cosmetics','c01')).availableQuantity).toBe(7);});
 it('requires current member and correct order ownership',async()=>{await g.register(member);const o=await order();await g.logout();await g.login('demo@example.invalid','demopass');await expect(g.getOrder(o.id)).rejects.toMatchObject({code:'NOT_FOUND'});});
});
describe('payment and shipping',()=>{
 it.each([['normal','paid'],['payment_failed','failed'],['payment_cancelled','cancelled'],['payment_unknown','unknown']] as const)('PayPay %s -> %s',async(scenario,status)=>{await g.register(member);const o=await order('cosmetics','paypay');g.setScenario(scenario);expect((await g.startPayment(o.id)).payment.status).toBe(status);});
 it('unknown payment blocks duplicate payment, method change and cancellation; status lookup resolves',async()=>{await g.register(member);const o=await order('cosmetics','paypay');g.setScenario('payment_unknown');await g.startPayment(o.id);await expect(g.startPayment(o.id)).rejects.toMatchObject({code:'PAYMENT_PENDING'});await expect(g.changePaymentMethod(o.id,'bank')).rejects.toMatchObject({code:'PAYMENT_PENDING'});await g.enterAdmin();await expect(g.adminOrder(o.id,'cancel','確認')).rejects.toMatchObject({code:'CONFLICT'});g.setScenario('normal');const paid=await g.checkPayment(o.id);expect(paid.payment.status).toBe('paid');expect(paid.payment.attempts).toBe(1);});
 it('bank manual confirmation, shipping failure/retry and tracking',async()=>{await g.register(member);const o=await order();await g.enterAdmin();await expect(g.adminOrder(o.id,'ship','確認',{carrier:'デモ便',tracking:'TEST'})).rejects.toMatchObject({code:'VALIDATION'});await g.adminOrder(o.id,'confirm_payment','デモ入金確認');g.setScenario('shipping_failed');expect((await g.adminOrder(o.id,'prepare','連携')).shipping.status).toBe('external_failed');g.setScenario('normal');expect((await g.adminOrder(o.id,'retry_shipping','再連携')).shipping.status).toBe('external_pending');const shipped=await g.adminOrder(o.id,'ship','発送確認',{carrier:'デモ便',tracking:'TEST001'});expect(shipped.shipping).toMatchObject({status:'shipped',tracking:'TEST001'});});
 it('refund adjusts paid referral sales; cancellation restores stock once',async()=>{await g.register({...member,referralCode:'DEMO10'});const o=await order();await g.enterAdmin();await g.adminOrder(o.id,'confirm_payment','確認');await g.adminOrder(o.id,'refund','返金確認');const sales=await g.getReferralSales(new Date().toISOString().slice(0,7));expect(sales[0]).toMatchObject({paidTotal:3465,adjustment:-3465});const c=await order();await g.adminOrder(c.id,'cancel','取消');await expect(g.adminOrder(c.id,'cancel','再取消')).rejects.toMatchObject({code:'CONFLICT'});expect((await g.getProduct('cosmetics','c01')).availableQuantity).toBe(7);});
});
describe('reviews and inquiries',()=>{
 it('multiple non-purchase reviews, public projection, moderation and self edit',async()=>{await g.register(member);const input={productId:'c01',rating:5,text:'公開確認用'};const first=await g.postReview(input);await g.postReview(input);expect((await g.getReviews('c01')).own).toHaveLength(2);await g.enterAdmin();await g.adminReview(first.id,'published','確認');let reviews=await g.getReviews('c01');expect(Object.keys(reviews.published.find(r=>r.id===first.id)!)).toEqual(['id','productId','nickname','age','rating','date','text']);await g.editReview(first.id,{...input,text:'編集後'});reviews=await g.getReviews('c01');expect(reviews.published.some(r=>r.id===first.id)).toBe(false);await g.deleteReview(first.id);expect((await g.getReviews('c01')).own.find(r=>r.id===first.id)?.status).toBe('hidden');await expect(g.getReviews('a01')).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('inquiry failure, retry idempotency and failed reply retry keep one record',async()=>{const input={business:'agriculture' as const,name:'確認',email:'test@example.invalid',subject:'件名',message:'本文',consent:true,idempotencyKey:'test'};g.setScenario('inquiry_failed');await expect(g.createInquiry(input)).rejects.toMatchObject({code:'NETWORK'});g.setScenario('normal');const i=await g.createInquiry(input);expect((await g.createInquiry(input)).id).toBe(i.id);await g.enterAdmin();g.setScenario('reply_failed');await expect(g.replyInquiry(i.id,'返信')).rejects.toMatchObject({code:'NETWORK'});let stored=(await g.getAdmin()).inquiries.find(n=>n.id===i.id)!;expect(stored.replies).toHaveLength(1);g.setScenario('normal');await g.replyInquiry(i.id,'返信',stored.replies[0].id);stored=(await g.getAdmin()).inquiries.find(n=>n.id===i.id)!;expect(stored.replies).toHaveLength(1);expect(stored.replies[0].status).toBe('sent');});
 it('denies readonly mutations and cross-business operations in gateway',async()=>{await g.enterAdmin();g.setAdminRole('readonly');await expect(g.adminProduct('c01',{saleStatus:'stopped'},'確認')).rejects.toMatchObject({code:'FORBIDDEN'});g.setAdminRole('agriculture');await expect(g.adminReview('review-demo','hidden','確認')).rejects.toMatchObject({code:'FORBIDDEN'});await expect(g.adminInquiry('INQ-DEMO','complete','担当')).rejects.toMatchObject({code:'FORBIDDEN'});expect((await g.getAdmin()).products.every(p=>p.business==='agriculture')).toBe(true);});
 it('distinguishes communication failure from business validation',async()=>{g.setScenario('network');await expect(g.listProducts({business:'cosmetics'})).rejects.toMatchObject({code:'NETWORK',retryable:true});});
});
