const {chromium,expect}=require('@playwright/test');const fs=require('fs');
const dir='qa/lower-finish';
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({reducedMotion:'reduce'});const results={sizes:[],checks:[]};
async function ready(w){await p.setViewportSize({width:w,height:1080});await p.goto('http://127.0.0.1:5177/');await p.locator('.ref-news-row').first().waitFor();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode()}))})}
try{for(const w of[1024,1440,1887,1920,768,390,320]){await ready(w);const g=await p.evaluate(()=>{
 const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};
 const contact=box('.ref-footer-contact'),shape=box('.ref-contact-contour'),wave=box('.ref-footer-surface');
 const path=new Path2D(document.querySelector('.ref-contact-contour path').getAttribute('d'));const context=document.createElement('canvas').getContext('2d');
 const textOnColor=[...document.querySelectorAll('.ref-footer-contact>.ref-contact-icon,.ref-footer-contact>span')].every(el=>{const r=el.getBoundingClientRect();return context.isPointInPath(path,(r.x+r.width/2-shape.x)*260/shape.w,(r.y+r.height/2-shape.y)*164/shape.h)});
 const leaf=document.querySelector('.ref-lower-decoration-news img'),c=document.createElement('canvas');c.width=leaf.naturalWidth;c.height=leaf.naturalHeight;const cx=c.getContext('2d');cx.drawImage(leaf,0,0);const data=cx.getImageData(0,0,c.width,c.height).data;
 const lr=leaf.getBoundingClientRect(),label=document.querySelector('.ref-news>.ref-text-link .corporate-action-label').getBoundingClientRect();let collisions=0;
 for(let y=Math.max(label.y,lr.y);y<Math.min(label.bottom,lr.bottom);y++)for(let x=Math.max(label.x,lr.x);x<Math.min(label.right,lr.right);x++){const ix=Math.floor((x-lr.x)/lr.width*c.width),iy=Math.floor((y-lr.y)/lr.height*c.height);if(data[(iy*c.width+ix)*4+3]>32)collisions++}
 return{width:innerWidth,scroll:document.documentElement.scrollWidth,contact,shape,wave,textOnColor,leafTextCollisions:collisions,values:box('.ref-values'),footer:box('.reference-footer'),scene:box('.ref-visual-story'),city:box('.ref-about-photo'),legacyLeaves:document.querySelectorAll('.ref-values-leaves,.ref-footer-leaves').length};
});
expect(g.scroll).toBe(w);expect(g.contact.right).toBeLessThanOrEqual(w+.1);expect(g.textOnColor).toBe(true);expect(g.leafTextCollisions).toBe(0);expect(g.legacyLeaves).toBe(0);expect(await p.locator('.ref-lower-decoration').count()).toBe(2);if(w>1000){expect(g.contact.w/g.contact.h).toBeGreaterThan(1.4);expect(g.contact.w/g.contact.h).toBeLessThanOrEqual(1.61);expect(g.wave.h).toBeGreaterThanOrEqual(24);expect(g.wave.h).toBeLessThanOrEqual(48)}
await p.screenshot({path:`${dir}/after/${w}-home.png`,fullPage:true});await p.screenshot({path:`${dir}/after/${w}-lower.png`,fullPage:true,clip:{x:0,y:g.values.y,width:w,height:g.footer.bottom-g.values.y}});results.sizes.push(g);
if(w===1887){await p.screenshot({path:`${dir}/after/1887-right-detail.png`,fullPage:true,clip:{x:w-560,y:g.values.y,width:560,height:g.footer.bottom-g.values.y}})}
// Long copy remains inside its action and visible contour; no fixed-height truncation.
await p.locator('.ref-footer-contact>span').first().evaluate(e=>e.textContent='暮らしや事業についてのお問い合わせ・ご相談をこちらから承ります。');const long=await p.locator('.ref-footer-contact').boundingBox();const label=await p.locator('.ref-footer-contact>span').first().boundingBox();expect(label.y+label.height).toBeLessThanOrEqual(long.y+long.height);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(w);
}
await ready(390);await p.locator('.ref-footer-contact').focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');await expect(p.locator('.ref-footer-contact')).toBeFocused();await p.locator('.ref-footer-contact').screenshot({path:dir+'/after/contact-keyboard.png'});await p.keyboard.press('Enter');await expect(p).toHaveURL(/\/contact$/);
results.checks=['Seven widths: curved footer, unclipped text, 52px+ action, no horizontal overflow','Leaf alpha does not intersect the news link label','Two different decorations; no repeated vertical leaf strips','Contact content sits within the SVG colored contour','Long contact copy expands at each width, keyboard Enter opens company contact'];console.log(JSON.stringify(results.sizes.map(s=>({width:s.width,ratio:s.contact.w/s.contact.h,wave:s.wave.h,leafTextCollisions:s.leafTextCollisions})),null,2));
}catch(e){results.failure=String(e);throw e}finally{fs.writeFileSync(dir+'/lower-results.json',JSON.stringify(results,null,2));await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
