const {chromium,expect}=require('@playwright/test');const Axe=require('@axe-core/playwright').default;const fs=require('fs');
const dir='qa/natural-layout';
(async()=>{fs.mkdirSync(dir+'/after',{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({reducedMotion:'reduce',locale:'ja-JP'});const p=await c.newPage();const report={screens:[],sizes:[],audits:[],checks:[],errors:[]};p.on('pageerror',e=>report.errors.push(e.message));await c.route(/IMG_7664|botanical-design\.jpg|provided-design\.png/,r=>r.abort());
const ready=async(w,h)=>{await p.setViewportSize({width:w,height:h});await p.goto('http://127.0.0.1:5177/');await p.locator('.ref-news-row').first().waitFor();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode()}))})};
const geometry=()=>p.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom}};return{width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,header:box('.site-header'),hero:box('.ref-hero'),photo:box('.ref-hero-photo'),business:box('.ref-business-duo'),about:box('.ref-about'),values:box('.ref-values'),news:box('.ref-news'),footer:box('.ref-footer-main'),heads:[box('.ref-cosmetics-copy h2'),box('.ref-agriculture-copy h2')],actions:[box('.ref-cosmetics-copy .ref-pill'),box('.ref-agriculture-copy .ref-pill')],font:getComputedStyle(document.querySelector('.reference-home')).fontSize,paddings:Object.fromEntries(['.ref-business-duo','.ref-about','.ref-values','.ref-news','.ref-footer-main'].map(s=>[s,[getComputedStyle(document.querySelector(s)).paddingTop,getComputedStyle(document.querySelector(s)).paddingBottom]]))}});
try{
for(const[w,h]of[[1440,900],[1920,900],[1920,1080],[1440,1080],[1024,900],[768,1024],[390,844],[320,740],[844,390]]){await ready(w,h);const g=await geometry();expect(g.scroll).toBe(w);if(w>1000){expect(g.header.height).toBeLessThanOrEqual(96);const fv=Math.min(880,Math.max(600,h-Math.min(110,Math.max(56,h*.09))));expect(g.hero.height).toBeGreaterThanOrEqual(fv-1);expect(g.hero.height).toBeLessThan(fv+1);expect(g.font).toBe('18px');expect(Math.abs(g.heads[0].y-g.heads[1].y)).toBeLessThan(1);expect(Math.abs(g.actions[0].y-g.actions[1].y)).toBeLessThan(1);const px=v=>parseFloat(v),within=(v,lo,hi)=>{expect(px(v)).toBeGreaterThanOrEqual(lo);expect(px(v)).toBeLessThanOrEqual(hi)};within(g.paddings['.ref-business-duo'][0],40,64);within(g.paddings['.ref-business-duo'][1],104,144);expect(g.paddings['.ref-values'][0]).toBe(g.paddings['.ref-values'][1]);within(g.paddings['.ref-values'][0],56,96);within(g.paddings['.ref-news'][0],56,96)}else{expect(g.font).toBe('17px');expect(g.photo.height).toBeGreaterThanOrEqual(280);expect(Math.abs(g.photo.height-g.hero.height)).toBeLessThan(2)}
for(const action of g.actions)expect(action.height).toBeGreaterThanOrEqual(52);
expect(await p.locator('.ref-news-row').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=64))).toBe(true);await expect(p.locator('.corporate-value')).toHaveCount(4);await expect(p.locator('.ref-news-row')).toHaveCount(3);await expect(p.locator('.corporate-panel')).toHaveCount(0);
const name=`${w}x${h}`;await p.screenshot({path:`${dir}/after/${name}-home.png`,fullPage:true});await p.screenshot({path:`${dir}/after/${name}-fv.png`});report.screens.push(name);report.sizes.push(g);
if(!(w===1920&&h===900)&&!(w===1440&&h===1080)&&w!==844){const a=await new Axe({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.audits.push({width:w,height:h,violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});expect(a.violations).toEqual([])}}
const pc=report.sizes.filter(s=>s.height===900&&s.width>=1440);// Spacing tokens scale with width up to their caps, so wide screens may gain a little air.
for(const key of['business','about','values','news'])expect(Math.abs(pc[0][key].height-pc[1][key].height)).toBeLessThan(48);report.checks.push('Nine viewports: FV fills the viewport minus a peek (600-880px), token spacing, aligned actions, stable 18px body on wide screens, stacked FV photograph spans the whole hero');
await ready(1440,900);const curves=await p.locator('.ref-business-edge').evaluateAll(es=>es.map(s=>({clip:s.querySelector('clipPath path').getAttribute('d'),edge:s.querySelector(':scope > path').getAttribute('d')})));for(const pair of curves)expect(pair.edge).toBe(pair.clip);report.checks.push('Each independent image mask and edge share the same local shape; source JPG blocked and UI remains selectable');
const text=await p.locator('h1').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);getSelection().removeAllRanges();getSelection().addRange(r);return getSelection().toString()});expect(text).toContain('未来');
for(const[w,h]of[[1440,900],[1920,1080],[1024,900],[768,1024],[390,844],[320,740],[844,390],[720,450],[960,540]]){await ready(w,h);if(w===720)await p.locator('.reference-home').evaluate(e=>e.querySelectorAll('h1,h2,h3,p,a').forEach(n=>n.style.fontSize=parseFloat(getComputedStyle(n).fontSize)*2+'px'));await p.locator('.ref-about-copy h2').evaluate(e=>e.textContent='ひらめきを大切に、地域の皆さまの暮らしのそばに寄り添う企業へ。');await p.locator('.ref-cosmetics-copy h2').evaluate(e=>e.textContent='毎日の肌に向き合いながら、やさしい未来へつながるひとときを。');await p.locator('.ref-news-title').first().evaluate(e=>e.textContent='地域の暮らしに寄り添うための取り組みについてお知らせします。長いタイトルでも文字を省略せずに表示します。');await p.locator('.ref-about-photo img').evaluate(async e=>{e.src='/images/reference-flower.png';await e.decode()});expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(w);const boxes=await p.locator('.ref-business-copy,.ref-about-copy').evaluateAll(es=>es.map(e=>[...e.querySelectorAll('.corporate-editorial-heading,.corporate-description,.corporate-action')].map(n=>{const r=n.getBoundingClientRect();return{top:r.top,bottom:r.bottom}})));for(const rows of boxes)for(let i=1;i<rows.length;i++)expect(rows[i].top).toBeGreaterThanOrEqual(rows[i-1].bottom-1);await p.screenshot({path:`${dir}/after/${w}x${h}-long-content.png`,fullPage:true})}report.checks.push('Long content, independent photo swap, landscape, zoom-equivalent reflow and doubled text preserve order without overflow or text/button overlap');
await ready(1440,900);const before=await p.locator('.ref-hero').boundingBox();await p.locator('h1').evaluate(e=>e.textContent='美しさと暮らしの未来を見つめながら、地域の皆さま一人ひとりに寄り添い、新しい毎日をともにつくっていきます。');const after=await p.locator('.ref-hero').boundingBox();expect(after.height).toBeGreaterThan(before.height);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(1440);report.checks.push('An unusually long hero heading grows its region rather than being clipped');
await ready(1024,900);const skip=p.getByRole('link',{name:'本文へ移動'});expect(await skip.evaluate(e=>getComputedStyle(e).clipPath)).toBe('inset(50%)');await p.keyboard.press('Tab');await expect(skip).toBeFocused();await p.screenshot({path:dir+'/after/keyboard-skip.png'});await p.keyboard.press('Enter');await expect(p.locator('#main-content')).toBeFocused();report.checks.push('Skip link is keyboard-only and transfers focus to the main content');
expect(report.errors).toEqual([]);
}catch(e){report.failure=String(e);await p.screenshot({path:dir+'/failure.png',fullPage:true});throw e}finally{fs.writeFileSync(dir+'/layout-results.json',JSON.stringify(report,null,2));await b.close()}console.log(JSON.stringify({checks:report.checks,screens:report.screens,audits:report.audits},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
