const {chromium,expect}=require('@playwright/test');const Axe=require('@axe-core/playwright').default;const fs=require('fs');
const dir='qa/lower-finish';
fs.mkdirSync(dir+'/after',{recursive:true});
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({reducedMotion:'reduce',locale:'ja-JP'});const p=await c.newPage();const result={sizes:[],audits:[],checks:[],errors:[]};p.on('pageerror',e=>result.errors.push(e.message));await c.route(/IMG_7664|botanical-design\.jpg|provided-design\.png/,r=>r.abort());
async function ready(w,h){await p.setViewportSize({width:w,height:h});await p.goto('http://127.0.0.1:5177/');await p.locator('.ref-news-row').first().waitFor();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode()}))})}
const geometry=()=>p.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom}};return{width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,header:box('.site-header'),scene:box('.ref-visual-story'),hero:box('.ref-hero'),photo:box('.ref-hero-photo'),product:box('.ref-hero-products'),business:box('.ref-business-duo'),about:box('.ref-about'),values:box('.ref-values'),news:box('.ref-news'),footer:box('.ref-footer-main'),heads:[box('.ref-cosmetics-copy h2'),box('.ref-agriculture-copy h2')],actions:[box('.ref-cosmetics-copy .ref-pill'),box('.ref-agriculture-copy .ref-pill')],font:getComputedStyle(document.querySelector('.reference-home')).fontSize}});
try{
for(const[w,h]of[[1024,900],[1440,900],[1920,1080],[1887,1080],[1440,1080],[768,1024],[390,844],[320,740],[844,390]]){await ready(w,h);const g=await geometry();expect(g.scroll).toBe(w);if(w>1000){expect(g.header.y).toBe(0);expect(g.font).toBe('18px');expect(g.scene.y).toBe(0);expect(g.about.y).toBe(g.scene.bottom);expect(await p.locator('.ref-city-art').evaluate(e=>Math.abs(e.getBoundingClientRect().right-innerWidth))).toBeLessThan(1);for(const head of g.heads){const lh=await p.locator('.ref-cosmetics-copy h2').evaluate(e=>parseFloat(getComputedStyle(e).lineHeight));expect(head.height).toBeLessThan(lh*2.2)}if(w===1024){expect(g.scene.height).toBeGreaterThanOrEqual(835);expect(g.scene.height).toBeLessThan(866);expect(g.values.y).toBeLessThan(1170);expect(g.news.y).toBeLessThan(1360);expect(g.footer.y).toBeLessThan(1550)}}else{expect(g.font).toBe('17px');expect(g.photo.height).toBeGreaterThanOrEqual(280);expect(g.photo.height).toBeLessThanOrEqual(420)}for(const action of g.actions)expect(action.height).toBeGreaterThanOrEqual(52);expect(await p.locator('.ref-news-row').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=52))).toBe(true);expect(await p.locator('.ref-business-ground').count()).toBe(0);
await p.screenshot({path:`${dir}/after/${w}x${h}-home.png`,fullPage:true});await p.screenshot({path:`${dir}/after/${w}x${h}-fv.png`});result.sizes.push(g);
if(w!==844&&!(w===1440&&h===1080)){const a=await new Axe({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();result.audits.push({width:w,violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});expect(a.violations).toEqual([])}}
result.checks.push('Nine sizes: full-bleed shared scene, overlaid desktop header, two-line business headings, reference density at 1024px, no overflow, 52px actions');
const a=result.sizes.find(s=>s.width===1440&&s.height===900),z=result.sizes.find(s=>s.width===1440&&s.height===1080);expect(a.scene.height).toBe(z.scene.height);result.checks.push('The same width has identical composition regardless of viewport height; 70svh rule removed');
await ready(1024,900);const paths=await p.locator('.ref-business-images').evaluate(e=>[...e.querySelectorAll('.ref-business-media')].map(media=>{const edge=media.querySelector('.ref-business-edge path');const key=edge.dataset.curve;const clip=[...e.querySelectorAll('clipPath')].find(c=>c.id.endsWith('-'+key));return{key,clip:clip.querySelector('path').getAttribute('d'),edge:edge.getAttribute('d')}}));paths.forEach(p=>expect(p.clip.startsWith(p.edge)).toBe(true));expect(paths.map(p=>p.key)).toEqual(['harvest','flower']);result.checks.push('Each photo owns its identical clip/stroke path; harvest starts underneath flower, with no separate overlaid border');
await p.locator('h1').evaluate(e=>{const range=document.createRange();range.selectNodeContents(e);getSelection().removeAllRanges();getSelection().addRange(range)});expect(await p.evaluate(()=>getSelection().toString())).toContain('未来');result.checks.push('Source reference JPG blocked; headings remain selectable and photos are standalone files');
for(const[w,h]of[[1024,900],[1440,900],[1920,1080],[768,1024],[390,844],[320,740],[844,390],[720,450],[960,540]]){await ready(w,h);if(w===720)await p.locator('.reference-home').evaluate(e=>e.querySelectorAll('h1,h2,h3,p,a').forEach(n=>n.style.fontSize=parseFloat(getComputedStyle(n).fontSize)*2+'px'));await p.locator('.ref-about-copy h2').evaluate(e=>e.textContent='ひらめきを大切に、地域の皆さまの暮らしのそばに寄り添う企業へ。');await p.locator('.ref-agriculture-copy h2').evaluate(e=>e.textContent='地域の大地の恵みを毎日の食卓へお届けする取り組み。');await p.locator('.ref-news-title').first().evaluate(e=>e.textContent='地域の暮らしに寄り添うための取り組みについてお知らせします。長いタイトルでも文字を省略せずに表示します。');await p.locator('.ref-about-photo img').evaluate(async e=>{e.src='/images/reference-flower.png';await e.decode()});expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(w);const boxes=await p.locator('.ref-business-copy,.ref-about-copy').evaluateAll(es=>es.map(e=>[...e.querySelectorAll('.corporate-editorial-heading,.corporate-description,.corporate-action')].map(n=>{const r=n.getBoundingClientRect();return{top:r.top,bottom:r.bottom}})));for(const rows of boxes)for(let i=1;i<rows.length;i++)expect(rows[i].top).toBeGreaterThanOrEqual(rows[i-1].bottom-1);await p.screenshot({path:`${dir}/after/${w}x${h}-long-content.png`,fullPage:true})}result.checks.push('Long headings and articles, independent photo replacement, doubled text, landscape and 200% equivalent reflow preserve content order');
await ready(1024,900);const before=await p.locator('.ref-hero').boundingBox();await p.locator('h1').evaluate(e=>e.textContent='美しさと暮らしの未来を見つめながら、地域の皆さま一人ひとりに寄り添い、新しい毎日をともにつくっていきます。');expect((await p.locator('.ref-hero').boundingBox()).height).toBeGreaterThan(before.height);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(1024);
await ready(1024,900);const skip=p.getByRole('link',{name:'本文へ移動'});expect(await skip.evaluate(e=>getComputedStyle(e).clipPath)).toBe('inset(50%)');await p.keyboard.press('Tab');await expect(skip).toBeFocused();await p.screenshot({path:dir+'/after/keyboard-skip.png'});await p.keyboard.press('Enter');await expect(p.locator('#main-content')).toBeFocused();result.checks.push('Long hero grows, skip link is keyboard-only and transfers focus');expect(result.errors).toEqual([]);
}catch(e){result.failure=String(e);await p.screenshot({path:dir+'/failure.png',fullPage:true});throw e}finally{fs.writeFileSync(dir+'/layout-results.json',JSON.stringify(result,null,2));await b.close()}console.log(JSON.stringify({checks:result.checks,audits:result.audits},null,2))})().catch(e=>{console.error(e);process.exitCode=1});
