const {chromium,expect}=require('@playwright/test');const fs=require('fs');
const dir='qa/reference-polish';
(async()=>{fs.mkdirSync(dir+'/after',{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({reducedMotion:'reduce'});const p=await c.newPage();const report={sizes:[],seams:[],focus:[]};const selectors=['.site-header','.ref-hero','.ref-hero-woman img','.ref-hero-products','.ref-business-art','.ref-cosmetics-copy','.ref-agriculture-copy','.ref-about','.ref-city-art','.ref-value-list','.ref-news','.ref-footer-main'];
const ready=async(w)=>{await p.setViewportSize({width:w,height:1080});await p.goto('http://127.0.0.1:5177/');await p.locator('.ref-news-row').first().waitFor();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode()}))})};
try{let base;
for(const width of [1024,1440,1888,1920]){await ready(width);const boxes=await p.evaluate(sels=>sels.map(s=>{const r=document.querySelector(s).getBoundingClientRect();return {selector:s,x:r.x*1024/innerWidth,y:r.y*1024/innerWidth,width:r.width*1024/innerWidth,height:r.height*1024/innerWidth}}),selectors);if(!base)base=boxes;for(let i=0;i<boxes.length;i++)for(const k of ['x','y','width','height'])expect(Math.abs(boxes[i][k]-base[i][k]),`${width} ${boxes[i].selector} ${k}`).toBeLessThan(1);const city=await p.locator('.ref-city-art').boundingBox();expect(Math.abs(city.x+city.width-width)).toBeLessThan(1);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);report.sizes.push({width,normalizedBoxes:boxes,cityRight:city.x+city.width});
const seams=await p.locator('.ref-business-art').evaluate(svg=>{const clips=[...svg.querySelectorAll('clipPath path')];return [...svg.querySelectorAll('.ref-business-seams use')].map(use=>{const path=document.getElementById(use.getAttribute('href').slice(1));const clip=clips[path.id.endsWith('harvest-crest')?1:0];let crossing=0;const samples=40;for(let i=1;i<samples;i++){const length=path.getTotalLength()*i/samples,a=path.getPointAtLength(length-.02),z=path.getPointAtLength(length+.02),q=path.getPointAtLength(length),dx=z.x-a.x,dy=z.y-a.y,n=Math.hypot(dx,dy);const left=new DOMPoint(q.x-dy/n*.25,q.y+dx/n*.25),right=new DOMPoint(q.x+dy/n*.25,q.y-dx/n*.25);if(clip.isPointInFill(left)!==clip.isPointInFill(right))crossing++}return {edge:path.id.split('-').slice(-2).join('-'),samples:samples-1,crossing,maximumTestOffsetReferencePx:.25}})});for(const e of seams)expect(e.crossing).toBe(e.samples);report.seams.push({width,edges:seams});}
await ready(1024);const skip=p.getByRole('link',{name:'本文へ移動'});expect(await skip.evaluate(e=>getComputedStyle(e).clipPath)).toBe('inset(50%)');await p.screenshot({path:dir+'/after/keyboard-normal.png'});await p.keyboard.press('Tab');await expect(skip).toBeFocused();expect(await skip.evaluate(e=>getComputedStyle(e).clipPath)).toBe('none');await p.screenshot({path:dir+'/after/keyboard-skip.png'});await p.keyboard.press('Enter');await expect(p.locator('#main-content')).toBeFocused();expect(await skip.evaluate(e=>getComputedStyle(e).clipPath)).toBe('inset(50%)');report.focus.push('通常非表示、Tab時表示、Enterで本文へフォーカス、移動後再び非表示');
await p.setViewportSize({width:960,height:540});await p.goto('http://127.0.0.1:5177/');await p.locator('.ref-news-row').first().waitFor();expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(960);report.zoom='1920px画面を200%拡大した時と同じ960 CSS pxで縦配置を確認。別の長文試験で文字サイズ2倍も確認。';
}finally{fs.writeFileSync(dir+'/geometry-and-focus.json',JSON.stringify(report,null,2));await b.close()}console.log('PASS uniform full-width geometry, shared seam boundaries, skip-link keyboard focus');})().catch(e=>{console.error(e);process.exitCode=1});
