const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const{chromium,expect}=require('@playwright/test');
const root=path.resolve('dist/share'),prefix='/ideanova-review/';const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.svg':'image/svg+xml','.woff2':'font/woff2','.woff':'font/woff'};
(async()=>{const requests=[],failures=[],errors=[],checks=[];const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local');requests.push({path:u.pathname,method:req.method});if(!u.pathname.startsWith(prefix)||req.method!=='GET'){res.writeHead(404);return res.end()};let f=path.resolve(root,decodeURIComponent(u.pathname.slice(prefix.length)));if(f!==root&&!f.startsWith(root+path.sep)){res.writeHead(404);return res.end()};if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end()};res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}${prefix}`;
const browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failures.push(r.url())});
async function ready(url){await p.goto(url);await p.locator('main h1').waitFor();await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode()}))});}
try{
 await ready(base);await expect(p.locator('.ref-news-row')).toHaveCount(3);await p.screenshot({path:'qa/share-preview/1440-home.png',fullPage:true});checks.push('Home, all independent photos, and 3 news rows served without a backend');
 const hero=await p.locator('.ref-visual-story').boundingBox();
 await p.locator('.corporate-primary-nav').getByRole('link',{name:'会社案内',exact:true}).click();await expect(p).toHaveURL(/#\/company$/);await p.reload();await expect(p.getByRole('heading',{name:'会社概要',exact:true})).toBeVisible();await p.goBack();await expect(p.locator('.ref-visual-story')).toBeVisible();checks.push('Hash navigation, direct reload and Back under a repository subdirectory');
 await p.locator('.ref-news-row').first().click();await expect(p.locator('.editorial article')).toBeVisible();await p.reload();await expect(p.locator('.editorial article img')).toBeVisible();checks.push('Real article route and image survive reload');
 await ready(base+'#/shop/agriculture?category=野菜');await expect(p.locator('.product-card')).toHaveCount(2);await p.getByRole('combobox',{name:'カテゴリー',exact:true}).selectOption('果物');await expect(p.locator('.product-card')).toHaveCount(1);checks.push('Agriculture products and category filtering');
 await ready(base);const pageCount=ctx.pages().length;await p.locator('.corporate-header-shop').click();await expect(p).toHaveURL(base+'cosmetics/#/');await expect(p.locator('.product-card')).toHaveCount(3);expect(ctx.pages().length).toBe(pageCount);await p.locator('.product-card').first().click();await expect(p).toHaveURL(/cosmetics\/#\/products\/c01$/);await p.reload();await expect(p.getByRole('heading',{name:'バランシング ローション',exact:true})).toBeVisible();await p.getByRole('button',{name:/^カートに入れる/}).click();await expect(p.getByRole('alert')).toContainText('デザイン確認用');await p.locator('.corporate-return').click();await expect(p.locator('.ref-visual-story')).toBeVisible();checks.push('Cosmetics opens in same tab, detail reload works, real purchase is unavailable, return to corporate works');
 await ready(base+'#/contact');await expect(p.getByRole('note')).toContainText('デザイン確認用');await p.locator('input[name=name]').fill('画面確認用');await p.locator('input[name=email]').fill('review@example.invalid');await p.locator('input[name=subject]').fill('表示確認');await p.locator('textarea[name=message]').fill('確認用の架空内容です');await p.locator('input[name=consent]').check();await p.getByRole('button',{name:/入力内容を確認する/}).click();await p.getByRole('button',{name:/この内容で送信する/}).click();await expect(p.getByRole('alert')).toContainText('入力内容は送信されません');checks.push('Inquiry confirmation retains design; submission is rejected locally without transmission');
 await ready(base+'#/shop/login');await p.locator('input[type=email]').fill('review@example.invalid');await p.locator('input[type=password]').fill('fictional-password');await p.getByRole('button',{name:/ログインする/}).click();await expect(p.getByRole('alert')).toContainText('デザイン確認用');expect(await p.evaluate(()=>localStorage.length)).toBe(0);expect((await ctx.cookies()).length).toBe(0);checks.push('Login unavailable, no storage or cookies');
 for(const route of['admin','preview']){await ready(base+'#/'+route);await expect(p.getByRole('heading',{name:'ページが見つかりません'})).toBeVisible();expect(p.url()).toContain(prefix+'#/not-found')};checks.push('Admin and test scenarios excluded from public preview');
 for(const w of[1024,768,390,320]){await p.setViewportSize({width:w,height:900});await ready(base);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(w);await p.screenshot({path:`qa/share-preview/${w}-home.png`,fullPage:true});}
 await p.getByRole('button',{name:'メニューを開く'}).click();await p.locator('#corporate-navigation').getByRole('link',{name:'会社案内',exact:true}).click();await expect(p).toHaveURL(/#\/company$/);checks.push('Responsive home and mobile menu');
 const api=requests.filter(r=>r.method!=='GET'||/demo-api/.test(r.path));expect(api).toEqual([]);expect(errors).toEqual([]);expect(failures).toEqual([]);checks.push('All requests are static GETs, no API requests, 404s or browser errors');
 fs.writeFileSync('qa/share-preview/results.json',JSON.stringify({checks,hero,apiRequests:api,errors,failures,base,requestCount:requests.length},null,2));console.log(JSON.stringify({checks:checks.length,errors,failures}));
}catch(e){await p.screenshot({path:'qa/share-preview/failure.png',fullPage:true});fs.writeFileSync('qa/share-preview/results.json',JSON.stringify({checks,errors,failures,error:String(e)},null,2));throw e}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
