import { useState } from 'react';
import { useGateway } from './GatewayContext';
import { Field, Empty } from './Shared';
import { MemberFields } from './MemberPages';
import { businessNames, type AdminSnapshot, type Article, type Category, type ShippingConfig, type Member, type MemberInput, type Referrer, type AdminIdentity, type Product } from './domain';
import type { Pending } from './AdminPages';
type Confirm = (p: Pending) => void;
export function ContentAdmin({ data, confirm }: {
    data: AdminSnapshot;
    confirm: Confirm;
}) { return <><h2>お知らせ・コラムの管理</h2><p>公開した記事だけが企業サイトに表示されます。画像は権利確認済みのデモ素材から選びます。</p>{data.articles.map(a => <details className="admin-record" key={a.id}><summary>{a.kind === 'news' ? 'お知らせ' : 'コラム'} / {a.title} / {a.published ? '公開' : '非公開'}</summary><ArticleEditor initial={a} confirm={confirm}/></details>)}<details className="admin-record"><summary>新しい記事を作成する</summary><ArticleEditor initial={{ id: '', kind: 'news', title: '', text: '', date: new Date().toISOString().slice(0, 10).replaceAll('-', '.'), category: 'お知らせ', image: 'koriyama', published: false }} confirm={confirm}/></details></>; }
function ArticleEditor({ initial, confirm }: {
    initial: Article;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [a, set] = useState(initial); return <form onSubmit={e => { e.preventDefault(); confirm({ title: '記事の保存・公開確認', details: `「${a.title}」を${a.published ? '公開' : '非公開'}で保存します。`, run: reason => gateway.saveArticle(a, reason) }); }}><div className="form-grid"><Field label="掲載先"><select value={a.kind} onChange={e => set({ ...a, kind: e.target.value as Article['kind'] })}><option value="news">お知らせ</option><option value="journal">コラム</option></select></Field><Field label="タイトル"><input required value={a.title} onChange={e => set({ ...a, title: e.target.value })}/></Field><Field label="日付"><input type="date" required value={a.date.replaceAll('.', '-')} onChange={e => set({ ...a, date: e.target.value.replaceAll('-', '.') })}/></Field><Field label="カテゴリー"><input required value={a.category} onChange={e => set({ ...a, category: e.target.value })}/></Field><Field label="画像"><select value={a.image} onChange={e => set({ ...a, image: e.target.value })}><option value="koriyama">郡山市街地（2015年）</option><option value="cosmetics">化粧品イメージ</option><option value="agriculture">農作物イメージ</option></select></Field></div><Field label="本文"><textarea required rows={6} value={a.text} onChange={e => set({ ...a, text: e.target.value })}/></Field><label className="check"><input type="checkbox" checked={a.published} onChange={e => set({ ...a, published: e.target.checked })}/>公開する</label><button className="button small">保存内容を確認する</button></form>; }
export function ProductDetailsAdmin({ data, confirm }: {
    data: AdminSnapshot;
    confirm: Confirm;
}) { return <><h2>商品情報・カテゴリーの編集</h2>{data.products.map(p => <details className="admin-record" key={p.id}><summary>{businessNames[p.business]} / {p.name} の情報を編集</summary><FullProduct initial={p} data={data} confirm={confirm}/></details>)}{data.shippingConfigs.map(c => <details className="admin-record" key={c.business}><summary>{businessNames[c.business]}の商品を新規作成</summary><FullProduct key={c.business} initial={{ id: '', business: c.business, name: '', category: data.categories.find(x => x.business === c.business)?.name || '', price: 0, size: '', description: '', images: [{ src: `/images/${c.business}.webp`, alt: '商品イメージ（サンプル）' }, { src: `/images/${c.business}.webp`, alt: '全体イメージ（サンプル）', position: 'center' }], saleStatus: 'stopped', availableQuantity: 0, inventoryTracked: true, fulfillment: c.business === 'cosmetics' ? 'external' : 'ideanova', producer: c.business === 'agriculture' ? { visible: false, name: '', description: '' } : undefined }} data={data} confirm={confirm}/></details>)}<h3>カテゴリー</h3>{data.categories.map(c => <CategoryEditor key={c.id} initial={c} confirm={confirm}/>)}{data.shippingConfigs.map(c => <CategoryEditor key={c.business} initial={{ id: '', business: c.business, name: '' }} confirm={confirm}/>)}</>; }
function FullProduct({ initial, data, confirm }: {
    initial: Product;
    data: AdminSnapshot;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [p, set] = useState(initial); return <form onSubmit={e => { e.preventDefault(); confirm({ title: '商品情報を保存', details: `${businessNames[p.business]} / ${p.name}。商品情報を更新します。金額変更は次の注文確認から反映されます。`, run: reason => gateway.saveProduct(p, reason) }); }}><div className="form-grid"><Field label="商品名"><input required value={p.name} onChange={e => set({ ...p, name: e.target.value })}/></Field><Field label="カテゴリー"><select value={p.category} onChange={e => set({ ...p, category: e.target.value })}>{data.categories.filter(c => c.business === p.business).map(c => <option key={c.id}>{c.name}</option>)}</select></Field><Field label="税込価格（デモ値）"><input type="number" required min={0} value={p.price} onChange={e => set({ ...p, price: Number(e.target.value) })}/></Field><Field label="内容量"><input required value={p.size} onChange={e => set({ ...p, size: e.target.value })}/></Field></div><Field label="商品説明"><textarea required value={p.description} onChange={e => set({ ...p, description: e.target.value })}/></Field><p>画像は複数登録に対応します。デモでは同一の権利確認済み素材の表示位置を切り替えます。本番では正式な商品別写真に置き換えます。</p><div className="form-grid">{p.images.map((image, i) => <Field label={`画像${i + 1}の説明`} key={i}><input required value={image.alt} onChange={e => set({ ...p, images: p.images.map((m, n) => n === i ? { ...m, alt: e.target.value } : m) })}/></Field>)}</div>{p.producer && <><Field label="生産者表示名"><input value={p.producer.name} onChange={e => set({ ...p, producer: { ...p.producer!, name: e.target.value } })}/></Field><Field label="生産者紹介"><textarea value={p.producer.description} onChange={e => set({ ...p, producer: { ...p.producer!, description: e.target.value } })}/></Field><label className="check"><input type="checkbox" checked={p.producer.visible} onChange={e => set({ ...p, producer: { ...p.producer!, visible: e.target.checked } })}/>生産者情報を表示する</label></>}<p className="caption">新規商品は販売停止・在庫0で作成します。上の販売条件から販売開始できます。</p><button className="button small">保存内容を確認する</button></form>; }
function CategoryEditor({ initial, confirm }: {
    initial: Category;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [name, set] = useState(initial.name); return <form className="admin-record actions" onSubmit={e => { e.preventDefault(); confirm({ title: 'カテゴリーを保存', details: `${businessNames[initial.business]} / ${name}。名称変更は所属商品にも反映されます。`, run: reason => gateway.saveCategory({ ...initial, name }, reason) }); }}><label>{businessNames[initial.business]} {initial.id ? 'カテゴリー名' : '新規カテゴリー名'}<input required value={name} onChange={e => set(e.target.value)}/></label><button className="button small secondary">保存を確認</button></form>; }
export function MembersAdmin({ data, confirm }: {
    data: AdminSnapshot;
    confirm: Confirm;
}) { return <><h2>共通会員の管理</h2><p>化粧品・農作物で共通の会員です。個人情報・紹介者の訂正は理由と履歴を残します。</p>{data.members.length ? data.members.map(m => <details className="admin-record" key={m.id}><summary>{m.name} / {m.email}</summary><MemberEditor member={m} confirm={confirm}/></details>) : <Empty title="会員管理の権限がありません"/>}</>; }
function MemberEditor({ member, confirm }: {
    member: Member;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [value, set] = useState<MemberInput>(member); const [code, setCode] = useState(member.referralCode || ''); return <form onSubmit={e => { e.preventDefault(); confirm({ title: '会員情報・紹介者を訂正', details: `${member.id} / ${value.name}。紹介者は${code || 'なし'}に変更します。過去の注文金額は変更しません。`, run: reason => gateway.adminMember(member.id, value, code, reason) }); }}><MemberFields value={value} onChange={set}/><Field label="紹介コード" optional><input value={code} onChange={e => setCode(e.target.value)}/></Field><button className="button small">訂正内容を確認する</button></form>; }
export function SettingsAdmin({ data, confirm }: {
    data: AdminSnapshot;
    confirm: Confirm;
}) { return <><h2>送料・発送案内</h2><p>基本送料と送料無料条件はデモの注文金額に反映します。地域ごとの実際の配送可否・追加送料・税処理は、本番仕様の確定と接続が必要です。</p>{data.shippingConfigs.map(c => <ShippingEditor key={c.business} initial={c} confirm={confirm}/>)}<h2>管理者と操作権限</h2><p>本番用の管理者登録・権限設計を確認する画面です。ログイン資格情報は発行しません。操作中のデモ権限は専用確認画面で切り替えます。</p>{data.administrators.map(a => <AdministratorEditor key={a.id} initial={a} confirm={confirm}/>)}{!!data.administrators.length && <AdministratorEditor initial={{ id: '', name: '', role: 'readonly', active: true }} confirm={confirm}/>}</>; }
function ShippingEditor({ initial, confirm }: {
    initial: ShippingConfig;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [value, set] = useState(initial); return <form className="admin-record" onSubmit={e => { e.preventDefault(); confirm({ title: '送料・発送案内を更新', details: `${businessNames[value.business]}の送料条件を変更します。進行中の注文は金額再確認の対象になります。`, run: reason => gateway.saveShipping(value, reason) }); }}><h3>{businessNames[value.business]}</h3><div className="form-grid"><Field label="基本送料（税込）"><input type="number" min={0} required value={value.fee} onChange={e => set({ ...value, fee: Number(e.target.value) })}/></Field><Field label="送料無料となる商品小計（割引前）" optional><input type="number" min={0} value={value.freeOver ?? ''} placeholder="空欄は条件なし" onChange={e => set({ ...value, freeOver: e.target.value === '' ? null : Number(e.target.value) })}/></Field></div><Field label="配送地域・追加条件の案内"><textarea required value={value.regionNote} onChange={e => set({ ...value, regionNote: e.target.value })}/></Field><Field label="発送の案内"><textarea required value={value.dispatchNote} onChange={e => set({ ...value, dispatchNote: e.target.value })}/></Field><button className="button small">保存を確認する</button></form>; }
function AdministratorEditor({ initial, confirm }: {
    initial: AdminIdentity;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [value, set] = useState(initial); return <form className="admin-record" onSubmit={e => { e.preventDefault(); confirm({ title: '管理者と権限を保存', details: `${value.name} / ${value.role} / ${value.active ? '有効' : '無効'}。これは管理情報のデモ登録です。`, run: reason => gateway.saveAdministrator(value, reason) }); }}><h3>{initial.id ? '管理者の編集' : '管理者の追加'}</h3><div className="form-grid"><Field label="管理者名"><input required value={value.name} onChange={e => set({ ...value, name: e.target.value })}/></Field><Field label="権限"><select value={value.role} onChange={e => set({ ...value, role: e.target.value as AdminIdentity['role'] })}><option value="full">全体管理</option><option value="cosmetics">化粧品担当</option><option value="agriculture">農作物担当</option><option value="readonly">閲覧のみ</option></select></Field></div><label className="check"><input type="checkbox" checked={value.active} onChange={e => set({ ...value, active: e.target.checked })}/>有効な管理者</label><button className="button small">権限変更を確認する</button></form>; }
export function ReferrersAdmin({ referrers, confirm }: {
    referrers: Referrer[];
    confirm: Confirm;
}) { return <><h3>紹介者の管理登録・承認</h3>{referrers.map(r => <ReferrerEditor key={r.id} initial={r} confirm={confirm}/>)}<ReferrerEditor initial={{ id: '', name: '', approved: false }} confirm={confirm}/></>; }
function ReferrerEditor({ initial, confirm }: {
    initial: Referrer;
    confirm: Confirm;
}) { const { gateway } = useGateway(); const [value, set] = useState(initial); return <form className="admin-record actions" onSubmit={e => { e.preventDefault(); confirm({ title: '紹介者の登録・承認', details: `${value.name} / ${value.approved ? '承認済み' : '未承認'}。未承認者のコードは適用対象外になります。`, run: reason => gateway.saveReferrer(value, reason) }); }}><label>{initial.id ? '紹介者名' : '新規紹介者名'}<input required value={value.name} onChange={e => set({ ...value, name: e.target.value })}/></label><label className="check"><input type="checkbox" checked={value.approved} onChange={e => set({ ...value, approved: e.target.checked })}/>承認済み</label><button className="button small secondary">登録・承認を確認する</button></form>; }
