import { useState } from 'react';
import { useGateway, useResource, useAction, ErrorBox, Loading, useDraft } from './GatewayContext';
import { Link, navigate } from './router';
import { businessNames, orderLabels, paymentLabels, shippingLabels, yen, type Business, type Address, type PaymentMethod, type Order } from './domain';
import { Heading, Crumbs, Empty, BusinessTabs, Totals, DemoNote, Field, Consent, Steps } from './Shared';
import { Quantity } from './ui';
type CheckoutDraft = {
    address: Address;
    method: PaymentMethod;
};
export function CartPage({ business }: {
    business: Business;
}) { const { gateway, carts, revision } = useGateway(); const action = useAction(); const lines = carts[business]; const r = useResource(async () => { const products = await Promise.all(lines.map(l => gateway.getProduct(business, l.productId))); let quote, error; try {
    if (lines.length)
        quote = await gateway.quoteCart(business);
}
catch (e) {
    error = e;
} return { products, quote, error }; }, [business, revision]); return <div className="container page"><Crumbs items={[{ label: 'ショップ', href: '/shop' }, { label: 'カート' }]}/><Heading title="ショッピングカート" lead={`${businessNames[business]}のお買い物をまとめて確認できます。商品の数量・価格・配送条件をご確認ください。`}/><BusinessTabs business={business} path="/shop/cart"/>{r.loading ? <Loading /> : r.error ? <ErrorBox error={r.error} retry={r.retry}/> : !lines.length ? <Empty title={`${businessNames[business]}のカートは空です`} href={`/shop/${business}`}>気になる商品を見つけて、カートに追加してください。</Empty> : <div className="cart-layout"><div><ErrorBox error={action.error}/>{lines.map(l => { const p = r.data?.products.find(p => p.id === l.productId); return p ? <article className="cart-row" key={p.id}><Link href={`/shop/${business}/products/${p.id}`}><img src={p.images[0].src} alt={p.images[0].alt} style={{ objectPosition: p.images[0].position }}/></Link><div><small>{p.category} / {p.size}</small><Link href={`/shop/${business}/products/${p.id}`}><h2>{p.name}</h2></Link><p>単価 {yen(p.price)}（税込）</p><span className="status-note">{p.saleStatus === 'stopped' ? '販売停止中' : p.inventoryTracked ? `現在の在庫 ${p.availableQuantity}点` : '在庫数の管理対象外'}</span><div className="actions"><Quantity value={l.quantity} max={p.inventoryTracked ? p.availableQuantity : 99} onChange={n => action.run(() => gateway.changeCart(business, p.id, n))}/><button className="text-button" disabled={action.busy} onClick={() => action.run(() => gateway.changeCart(business, p.id, 0))}>削除する</button></div></div><strong>{yen(p.price * l.quantity)}</strong></article> : null; })}<Link className="line-link" href={`/shop/${business}`}>お買い物を続ける <span>←</span></Link></div><aside className="order-summary"><h2>{businessNames[business]}のお会計</h2><ErrorBox error={r.data?.error} retry={r.retry}/>{r.data?.quote && <><Totals value={r.data.quote}/>{r.data.quote.referral && <p className="caption">{r.data.quote.referral.message}</p>}<Link className="button full" href={`/shop/checkout?business=${business}`}>購入手続きへ <span>→</span></Link></>}<p>{business === 'cosmetics' ? 'メーカー・外部発送先' : 'IdeaNova'}から発送します。</p><p className="caption">確定前に最新の価格・割引・在庫を確認します。</p></aside></div>}<DemoNote /></div>; }
export function CheckoutPage({ business }: {
    business: Business;
}) { const { gateway, member, carts } = useGateway(); const initial = { address: { name: member?.name || '', postal: '', address: member?.address || '', phone: member?.phone || '' }, method: 'bank' as PaymentMethod }; const [draft, setDraft, clearDraft] = useDraft<CheckoutDraft>(`checkout:${member?.id || "guest"}:${business}`, initial); const [step, setStep] = useState(0); const [consent, setConsent] = useState(false); const [key] = useState(() => crypto.randomUUID()); const action = useAction(); const r = useResource(() => gateway.quoteCart(business), [business, member?.id]); const update = (value: CheckoutDraft) => { setDraft(value); }; const submit = () => action.run(() => gateway.createOrder({ quoteId: r.data!.id, address: draft.address, paymentMethod: draft.method, idempotencyKey: key, consent }), o => { clearDraft(); navigate(`/shop/orders/${o.id}`); }); return <div className="container page"><Crumbs items={[{ label: 'ショップ', href: '/shop' }, { label: 'カート', href: `/shop/cart?business=${business}` }, { label: '購入手続き' }]}/><Heading title={`${businessNames[business]}の購入手続き`}/><Steps current={step}/>{!member ? <div className="notice"><h2>ご注文の確定には会員ログインが必要です。</h2><p>ログイン・登録後は、この購入手続きに戻ります。カートは保存されています。</p><div className="actions"><Link className="button" href={`/shop/login?next=${encodeURIComponent(`/shop/checkout?business=${business}`)}`}>ログインして続ける →</Link><Link className="button secondary" href={`/shop/register?next=${encodeURIComponent(`/shop/checkout?business=${business}`)}`}>新規会員登録 →</Link></div></div> : !carts[business].length ? <Empty title="カートに商品がありません" href={`/shop/${business}`}/> : r.loading ? <Loading /> : r.error ? <><ErrorBox error={r.error} retry={r.retry}/><Link className="button secondary" href={`/shop/cart?business=${business}`}>カートを修正する →</Link></> : r.data && <form className="checkout-layout" onSubmit={e => { e.preventDefault(); if (step === 0) {
    setStep(1);
    setConsent(false);
    window.scrollTo(0, 0);
}
else
    submit(); }}><div><section className="form-section"><div className="section-top"><h2>お届け先</h2>{step === 1 && <button type="button" className="text-button" onClick={() => setStep(0)}>修正する</button>}</div>{step === 0 ? <div className="form-grid">{(['name', 'postal', 'address', 'phone'] as const).map(k => <Field key={k} label={{ name: 'お名前', postal: '郵便番号', address: 'ご住所', phone: '電話番号' }[k]}><input required autoComplete={{ name: 'name', postal: 'postal-code', address: 'street-address', phone: 'tel' }[k]} value={draft.address[k]} onChange={e => update({ ...draft, address: { ...draft.address, [k]: e.target.value } })}/></Field>)}</div> : <address>{draft.address.name}<br />〒{draft.address.postal}<br />{draft.address.address}<br />{draft.address.phone}</address>}</section><section className="form-section"><div className="section-top"><h2>お支払い方法</h2>{step === 1 && <button type="button" className="text-button" onClick={() => setStep(0)}>修正する</button>}</div>{step === 0 ? <div className="payment-options">{(['bank', 'paypay'] as const).map(method => <label key={method} className="radio-card"><input type="radio" name="payment" value={method} checked={draft.method === method} onChange={() => update({ ...draft, method })}/><span><strong>{method === 'bank' ? '銀行振込' : 'PayPay'}</strong><small>{method === 'bank' ? '受付後に振込先をご案内。管理者の入金確認後に発送します。' : '受付後にお支払いへ進みます。結果不明時は状態照会で確認します。'}</small></span></label>)}</div> : <p>{draft.method === 'bank' ? '銀行振込' : 'PayPay'}</p>}<p className="caption">このプレビューでは実際のお支払いは発生しません。</p></section><section className="form-section"><h2>ご注文の商品</h2>{r.data.items.map(l => <div className="confirmation-item" key={l.productId}><strong>{l.name}</strong><span>数量 {l.quantity}点 × 単価 {yen(l.unitPrice)}</span><span>割引 −{yen(l.discount)} / 小計 {yen(l.total)}</span></div>)}<Link className="text-link" href={`/shop/cart?business=${business}`}>商品・数量を修正する →</Link></section></div><aside className="order-summary"><h2>{step === 0 ? 'お支払い金額' : '注文内容の最終確認'}</h2><Totals value={r.data}/><p>{business === 'cosmetics' ? '外部発送先' : 'IdeaNova'}から発送します。発送時期は正式情報の確認中です。</p>{r.data.referral && <p>{r.data.referral.message}</p>}<ErrorBox error={action.error}/>{!!action.error && <div className="actions"><button type="button" className="text-button" onClick={() => { r.retry(); action.clear(); setStep(0); }}>最新金額を再確認</button><Link className="text-link" href={`/shop/cart?business=${business}`}>カートの修正へ</Link></div>}{step === 1 && <Consent checked={consent} onChange={setConsent} text="商品・数量・金額・配送先・支払い方法を確認し、注文に同意する"/>}<button className="button full" disabled={action.busy || step === 1 && !consent}>{action.busy ? '確認しています…' : step === 0 ? '注文内容を確認する' : 'デモ注文を確定する'} <span>→</span></button>{step === 1 && <button type="button" className="text-button" onClick={() => setStep(0)}>入力画面へ戻る</button>}<DemoNote /></aside></form>}</div>; }
export function OrderInformation({ order: o }: {
    order: Order;
}) { return <><div className="order-statuses"><span>{businessNames[o.business]}</span><span>注文：{orderLabels[o.status]}</span><span>支払い：{paymentLabels[o.payment.status]}</span><span>発送：{shippingLabels[o.shipping.status]}</span></div><div className="order-detail-grid"><section><h2>ご注文内容</h2>{o.items.map(l => <div className="confirmation-item" key={l.productId}><strong>{l.name}</strong><span>{l.quantity}点 × {yen(l.unitPrice)} / 割引 −{yen(l.discount)}</span><span>{yen(l.total)}</span></div>)}<Totals value={o}/></section><section><h2>配送先・発送情報</h2><address>{o.address.name}<br />〒{o.address.postal}<br />{o.address.address}<br />{o.address.phone}</address><dl className="information"><div><dt>発送元</dt><dd>{o.shipping.fulfillment === 'external' ? 'メーカー・外部発送先' : 'IdeaNova'}</dd></div><div><dt>配送状態</dt><dd>{shippingLabels[o.shipping.status]}</dd></div><div><dt>配送会社</dt><dd>{o.shipping.carrier || '未確定'}</dd></div><div><dt>追跡番号</dt><dd>{o.shipping.tracking || '発送後にご案内'}</dd></div></dl></section></div></>; }
export function OrderPage({ id }: {
    id: string;
}) { const { gateway, member, revision } = useGateway(); const r = useResource(() => gateway.getOrder(id), [id, member?.id, revision]); const action = useAction(); if (!member)
    return <div className="container page"><Heading title="ご注文の確認"/><Link className="button" href={`/shop/login?next=${encodeURIComponent(`/shop/orders/${id}`)}`}>ログインして確認する →</Link></div>; const o = r.data; return <div className="container page"><Crumbs items={[{ label: 'ショップ', href: '/shop' }, { label: '会員ページ', href: '/shop/account' }, { label: '注文詳細' }]}/><Heading title="ご注文の確認" lead={`注文番号：${id}`}/>{r.loading && !o ? <Loading /> : r.error ? <ErrorBox error={r.error} retry={r.retry}/> : o && <><Steps current={2}/><section className="payment-result" aria-live="polite"><h2>{o.payment.status === 'paid' ? 'お支払いを確認しました。' : o.payment.status === 'unknown' ? 'お支払い結果を確認しています。' : o.payment.status === 'processing' ? 'お支払いを処理しています。' : o.status === 'refunded' ? '返金済みのご注文です。' : o.status === 'cancelled' ? '取り消されたご注文です。' : 'ご注文を受け付けました。'}</h2><p>支払方法：{o.payment.method === 'bank' ? '銀行振込' : 'PayPay'} / {paymentLabels[o.payment.status]}</p>{o.status === 'awaiting_payment' && o.payment.method === 'bank' && <div className="bank-guide"><h3>銀行振込のご案内</h3><p>銀行・支店・口座番号・名義・振込期限は未確定です。本番ではここに正式な振込情報を表示します。この画面から振り込まないでください。</p><p>振込予定額 <strong>{yen(o.total)}</strong> ／現在は入金待ちです。管理者による入金確認後に状態が更新されます。</p></div>}{['unknown', 'processing'].includes(o.payment.status) ? <><p>二重のお支払いを防ぐため、再決済や支払方法の変更はできません。結果を確認するまでお待ちください。</p><button className="button" disabled={action.busy} onClick={() => action.run(() => gateway.checkPayment(id))}>支払い状況を確認する →</button></> : o.status === 'awaiting_payment' && <><p>{o.payment.status === 'failed' ? 'お支払いに失敗しました。注文内容は保持しています。' : o.payment.status === 'cancelled' ? 'お支払いが取り消されました。注文内容を確認して再開できます。' : 'この先もデモとして動作します。'}</p><div className="actions">{o.payment.method === 'paypay' && <button className="button" disabled={action.busy} onClick={() => action.run(() => gateway.startPayment(id))}>{action.busy ? '決済を処理しています…' : 'PayPayのデモ支払いへ'} →</button>}<button className="text-button" disabled={action.busy} onClick={() => action.run(() => gateway.changePaymentMethod(id, o.payment.method === 'bank' ? 'paypay' : 'bank'))}>{o.payment.method === 'bank' ? 'PayPay' : '銀行振込'}に変更する</button></div></>}<ErrorBox error={action.error}/></section><OrderInformation order={o}/><div className="actions"><Link className="button secondary" href="/shop/account">注文履歴へ →</Link><Link className="text-link" href={`/shop/contact?business=${o.business}&order=${o.id}`}>この注文について問い合わせる →</Link></div><DemoNote /></>}</div>; }
