import { useId, useLayoutEffect, useState, type RefObject, type ReactNode, type CSSProperties } from 'react';

export const corporateImages = {
  city: '/images/koriyama.webp',
  heroBackground: '/images/hero-botanical-person-free.webp',
  products: '/images/reference-products.webp',
  ground: '/images/reference-natural-underlay.png',
  stone: '/images/reference-stone-repair.png',
  flower: '/images/reference-flower-finish.webp',
  harvest: '/images/reference-harvest.webp',
  botanical: '/images/reference-leaves.webp',
  botanicalEdge: '/images/reference-botanical-edge.webp',
  scenery: '/images/reference-city.webp',
  valuesStillLife: '/images/reference-values-still-life.webp',
  footerSprig: '/images/reference-footer-sprig.webp',
  cosmetics: '/images/ui-cosmetics.png',
  tomatoes: '/images/ui-tomatoes.png',
  basket: '/images/ui-basket.webp',
  fruit: '/images/ui-fruit.png',
  meal: '/images/ui-meal.png',
  towels: '/images/ui-towels.png',
} as const;

/** WebP artwork generated by scripts/optimize-images.mjs at 800px and full width. */
export function responsiveSet(src: string) {
  return /^\/images\/(hero-botanical-person-free|reference-[a-z-]+|ui-basket)\.webp$/.test(src) ? `${src.replace(/\.webp$/, '-800.webp')} 800w, ${src} 1600w` : undefined;
}

// Shapes use the component's own bounds, independent of the source photograph.
const shapes = {
  cityWave: 'M.24 .035 C.46 -.045 .80 -.035 1 .025 L1 .94 C.88 1.01 .81 .96 .72 .97 C.54 1.015 .21 .925 .075 .74 C-.085 .515 .02 .18 .24 .035 Z',
  cosmetics: 'M0 1 L0 .95 C0 .78 .26 .62 .42 .55 C.54 .49 .50 .20 .62 .06 C.66 .01 .68 0 .72 0 H1 V1 Z',
  harvest: 'M0 1 C.025 .58 .12 .29 .27 .13 C.36 .035 .45 0 .55 0 H1 V1 Z',
  soft: 'M0 1 V.75 C0 .34 .12 .06 .26 0 H1 V1 Z',
  tomatoes: 'M.78 0 C.625 .25 .67 .74 .37 1 H1 V0 Z',
  heroCosmetics: 'M.93 0 C.745 .31 .87 .71 .62 1 H1 V0 Z',
} as const;
export type PhotoShape = keyof typeof shapes;
export type CorporatePhotoProps = {
  src: string; alt?: string; position?: string; shape?: PhotoShape; className?: string; eager?: boolean;
  srcSet?: string; sizes?: string; ratio?: CSSProperties['aspectRatio']; fit?: 'cover' | 'contain'; fetchPriority?: 'high' | 'low' | 'auto';
};
export function CorporatePhoto({ src, alt = '', position = 'center', shape, className = '', eager = false, srcSet, sizes, ratio, fit = 'cover', fetchPriority }: CorporatePhotoProps) {
  const id = useId();
  const style: CSSProperties = { '--photo-position': position, '--photo-fit': fit, aspectRatio: ratio, clipPath: shape ? `url(#${id})` : undefined } as CSSProperties;
  return <div className={`reference-photo ${className}`} style={style}>
    {shape && <svg className="ref-svg-definitions" aria-hidden="true" focusable="false"><defs><clipPath id={id} clipPathUnits="objectBoundingBox"><path d={shapes[shape]} /></clipPath></defs></svg>}
    <img src={src} alt={alt} width={1536} height={1024} srcSet={srcSet ?? responsiveSet(src)} sizes={sizes ?? '(max-width: 1000px) 100vw, 60vw'}
      loading={eager ? 'eager' : 'lazy'} fetchPriority={fetchPriority ?? (eager ? 'high' : undefined)} decoding="async" />
  </div>;
}

// All photographic seams derive from the rendered product, including when copy grows.
export const sceneLayout = { '--city-overlap': 'clamp(36px, 4vw, 64px)' } as CSSProperties;
/** mobile is 1 while the stacked (≤1000px) composition is active. */
export type SceneGeometry = { width: number; height: number; hero: number; x: number; y: number; pw: number; ph: number; copyBottom: number; mobile: number };
const initialScene: SceneGeometry = { width: 1024, height: 900, hero: 540, x: 280, y: 260, pw: 660, ph: 440, copyBottom: 420, mobile: 0 };
const stackedQuery = '(max-width: 1000px)';
export function useSceneGeometry(ref: RefObject<HTMLDivElement | null>) {
  const [geometry, setGeometry] = useState(initialScene);
  useLayoutEffect(() => {
    const root = ref.current;
    if (!root) return;
    const scene = root.querySelector<HTMLElement>('.ref-visual-story')!;
    const hero = root.querySelector<HTMLElement>('.ref-hero')!;
    const product = root.querySelector<HTMLElement>('.ref-hero-products')!;
    const copy = root.querySelector<HTMLElement>('.ref-hero-copy')!;
    const read = () => {
      const r = scene.getBoundingClientRect(), h = hero.getBoundingClientRect(), p = product.getBoundingClientRect(), c = copy.getBoundingClientRect();
      const next = { width: r.width, height: r.height, hero: h.bottom-r.top, x: p.left-r.left, y: p.top-r.top, pw: p.width, ph: p.height, copyBottom: c.bottom-r.top, mobile: matchMedia(stackedQuery).matches ? 1 : 0 };
      setGeometry(old => Object.keys(next).every(k => Math.abs(old[k as keyof SceneGeometry]-next[k as keyof SceneGeometry]) < .25) ? old : next);
    };
    const observer = new ResizeObserver(read);
    [scene, hero, product, copy].forEach(el => observer.observe(el));
    read();
    // Web fonts change the copy height after first paint; measure again once they settle.
    document.fonts?.ready.then(read);
    return () => observer.disconnect();
  }, [ref]);
  return geometry;
}
export function scenePaths(g: SceneGeometry) {
  const { width: w, height: h, hero: b, x, y, pw, ph } = g;
  // Source containers end above 78% of the product photo; seams touch only the stone below.
  const jx=x+pw*.58, jy=y+ph*.91;
  const flower=`M0 ${b-50} C${w*.14} ${b-120} ${x+pw*.16} ${y+ph*.65} ${x+pw*.30} ${y+ph*.84} C${x+pw*.42} ${y+ph} ${w*.48} ${h-70} ${w*.62} ${h-24}`;
  const harvest=`M${x+pw*.03} ${y+ph*.84} C${x+pw*.24} ${y+ph*.87} ${x+pw*.45} ${jy+ph*.015} ${jx} ${jy} C${x+pw*.76} ${jy-ph*.02} ${x+pw*.90} ${y+ph*.84} ${w} ${b-66}`;
  const lowerRight=`L${w} ${h-32} C${w*.91} ${h+8} ${w*.76} ${h} ${w*.62} ${h-24}`;
  const lowerLeft=`C${w*.38} ${h-28} ${w*.16} ${h-40} 0 ${h}`;
  return { flower, harvest,
    flowerFill:`${flower} ${lowerLeft} Z`,
    harvestFill:`${harvest} ${lowerRight} L${x+pw*.03} ${h} Z`,
    outline:`M0 0 H${w} ${lowerRight} ${lowerLeft} Z`,
  };
}

export function HeroPhotographs({ geometry }: { geometry: SceneGeometry }) {
  const id = useId();
  const { width:w, height:h, hero:b, copyBottom, mobile }=geometry;
  // The stacked layout keeps the same paper sweep and green band, turned to run beneath the copy.
  const paperBottom=mobile ? Math.min(copyBottom+132,b-120) : Math.max(copyBottom+120,b-70);
  const paperPath=(bottom:number) => mobile
    ? `M0 0 H${w} V${bottom-64} C${w*.74} ${bottom-4} ${w*.42} ${bottom-58} ${w*.18} ${bottom-18} C${w*.09} ${bottom-4} ${w*.03} ${bottom+4} 0 ${bottom+12} Z`
    : `M0 0 H${w*.64} C${w*.55} ${bottom*.14} ${w*.58} ${bottom*.59} ${w*.49} ${bottom*.85} C${w*.38} ${bottom*1.12} ${w*.12} ${bottom*1.04} 0 ${bottom*.55} Z`;
  const washHeight=mobile ? b : h;
  return <div className="ref-hero-photo" aria-hidden="true" style={{clipPath:`url(#${id}-scene)`, '--hero-photo-height':`${b}px`} as CSSProperties}>
    <svg className="ref-svg-definitions" focusable="false"><defs><clipPath id={`${id}-scene`} clipPathUnits="objectBoundingBox"><path transform={`scale(${1/w} ${1/h})`} d={scenePaths(geometry).outline}/></clipPath></defs></svg>
    <CorporatePhoto className="ref-hero-botanical" src={corporateImages.heroBackground} eager fetchPriority="auto" sizes="100vw" />
    <svg className="ref-hero-wash" viewBox={`0 0 ${w} ${washHeight}`} preserveAspectRatio="none" focusable="false">
      <defs><linearGradient id={`${id}-paper`} x1="0" x2="1"><stop offset="0" stopColor="#f8f5ee" /><stop offset=".76" stopColor="#f8f5ee" stopOpacity=".97" /><stop offset="1" stopColor="#f8f5ee" stopOpacity=".75" /></linearGradient></defs>
      <path fill="#173f2ee8" d={paperPath(paperBottom+(mobile ? 30 : 72))} />
      <path fill={`url(#${id}-paper)`} d={paperPath(paperBottom)} />
    </svg>
  </div>;
}
export function HeroProducts() {
  return <CorporatePhoto className="ref-hero-products" src={corporateImages.products} alt="化粧水・クリーム・チューブの化粧品イメージ。正式商品ではありません" fit="contain" eager />;
}
export function BusinessPhotographs({ geometry, flower = corporateImages.flower, harvest = corporateImages.harvest }: { geometry: SceneGeometry; flower?: string; harvest?: string }) {
  const id = useId();
  const paths = scenePaths(geometry);
  const {width:w,height:h,hero:b}=geometry;
  return <div className="ref-business-images" aria-hidden="true" style={{'--business-photo-top':`${b-Math.max(120,geometry.ph*.3)}px`, clipPath:`url(#${id}-outline)`} as CSSProperties}>
    <svg className="ref-svg-definitions" focusable="false"><defs>
      <clipPath id={`${id}-outline`} clipPathUnits="objectBoundingBox"><path transform={`scale(${1/w} ${1/h})`} d={paths.outline} /></clipPath>
      {(['flower', 'harvest'] as const).map(key => <clipPath id={`${id}-${key}`} clipPathUnits="objectBoundingBox" key={key}><path transform={`scale(${1/w} ${1/h})`} d={paths[`${key}Fill`]} /></clipPath>)}
    </defs></svg>
    {([{ key: 'harvest', src: harvest }, { key: 'flower', src: flower }] as const).map(({ key, src }) =>
      <div className={`ref-business-media ref-${key}-image`} key={key} style={{ clipPath: `url(#${id}-${key})` }}>
        <CorporatePhoto src={src} position={key === 'harvest' ? 'center' : 'center 45%'} />
        <div className="ref-business-tint" />
        <svg className="ref-business-edge" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" focusable="false">
          <path data-curve={key} d={paths[key]} fill="none" stroke="#f8f5ee" strokeWidth="2" vectorEffect="non-scaling-stroke" />
        </svg>
      </div>
    )}
  </div>;
}

export function LeafMark() {
  return <svg className="corporate-leaf-mark" viewBox="0 0 52 64" aria-hidden="true" focusable="false" fill="currentColor">
    <path d="M18 58C-1 40 5 25 22 13C16 29 33 38 18 58Z" />
    <path d="M29 46C46 35 50 17 39 2C43 22 20 26 29 46Z" />
  </svg>;
}

export function BotanicalDecoration({ className = '' }: { className?: string }) {
  return <span className="ref-botanical-frame" aria-hidden="true"><img className={`ref-botanical ${className}`} src={className === 'ref-about-leaves' ? corporateImages.botanical : corporateImages.botanicalEdge} srcSet={responsiveSet(className === 'ref-about-leaves' ? corporateImages.botanical : corporateImages.botanicalEdge)} sizes="25vw" alt="" loading="lazy" decoding="async" width="1024" height="1536" /></span>;
}

export function LeafDecoration({ className = '' }: { className?: string }) {
  return <svg className={`ref-leaf-decoration ${className}`} viewBox="0 0 180 360" fill="none" aria-hidden="true" focusable="false">
    <path d="M16 360 C70 255 113 120 69 0" stroke="currentColor" strokeWidth="3" />
    {[{x:65,y:32,a:-18},{x:76,y:84,a:9},{x:80,y:141,a:18},{x:70,y:197,a:30},{x:51,y:252,a:36},{x:28,y:312,a:44}].map(({x,y,a},i) => <g key={i} transform={`translate(${x} ${y}) rotate(${a})`} fill="currentColor">
      <path d="M0 0 C-44 -5 -68 -28 -60 -58 C-22 -54 -1 -33 0 0Z" />
      <path d="M0 10 C36 -31 62 -30 81 -19 C64 14 30 26 0 10Z" />
    </g>)}
  </svg>;
}

/** Live text kept separate from the photograph and its clipping path. */
export function PhotoNote({ children, overlay = false }: { children: ReactNode; overlay?: boolean }) {
  return overlay ? <p className="ref-photo-message">{children}</p> : <div className="corporate-photo-note"><p className="ref-handwriting">{children}</p></div>;
}
/** Lower-page decoration is independent from the articles and value items. */
export function LowerDecoration({ variant }: { variant: 'values' | 'news' }) {
  return <span className={`ref-lower-decoration ref-lower-decoration-${variant}`} aria-hidden="true">
    <img src={variant === 'values' ? corporateImages.valuesStillLife : corporateImages.footerSprig} srcSet={responsiveSet(variant === 'values' ? corporateImages.valuesStillLife : corporateImages.footerSprig)} sizes="30vw" width={variant === 'values' ? 1536 : 1254} height={variant === 'values' ? 1024 : 1254} alt="" loading="lazy" decoding="async" />
  </span>;
}
export function FooterCurve() {
  return <svg className="ref-footer-surface" viewBox="0 0 1024 48" preserveAspectRatio="none" aria-hidden="true" focusable="false">
    <path d="M0 10 C280 43 628 45 1024 8 V48 H0 Z" />
  </svg>;
}
export function ContactContour() {
  return <svg className="ref-contact-contour" viewBox="0 0 260 164" preserveAspectRatio="none" aria-hidden="true" focusable="false">
    <path d="M100 4 C155 4 220 18 260 40 V164 H46 C24 164 4 136 4 110 C4 84 7 35 23 20 C39 5 76 4 100 4 Z" />
  </svg>;
}
