import { useState } from 'react';
import { isCosmetics } from './site';
import { useGateway, useAction, ErrorBox, useDraft } from './GatewayContext';
import { Link } from './router';
import { type InquiryBusiness, businessNames } from './domain';
import { Heading, Crumbs, Field, Consent, Steps, DemoNote } from './Shared';
export function InquiryPage({ business, orderId = '' }: {
    business: InquiryBusiness;
    orderId?: string;
}) { const { gateway, member } = useGateway(); const action = useAction(); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const draftKey = `inquiry:${member?.id || "guest"}:${business}`; const [form, setForm, clearForm] = useDraft(draftKey, { name: member?.name || '', email: member?.email || '', subject: '', message: '', orderId }); const [consent, setConsent] = useDraft(draftKey + ":consent", false); const [step, setStep] = useState(0); const [receipt, setReceipt] = useState(''); const [key] = useDraft(draftKey + ":key", crypto.randomUUID()); const title = business === 'corporate' ? '会社へのお問い合わせ' : `${businessNames[business]}のお問い合わせ`; return <div className="container page narrow"><Crumbs items={business === 'corporate' ? [{ label: 'お問い合わせ' }] : [{ label: 'ショップ', href: '/shop' }, { label: 'お問い合わせ' }]}/><Heading title={title} lead={business === 'corporate' ? '事業・会社についてのご相談を承ります。' : '商品・ご注文・配送に関するご相談を承ります。'}/>{!isCosmetics && <nav className="contact-doors" aria-label="お問い合わせ窓口"><Link aria-current={business === 'corporate' ? 'page' : undefined} href="/contact">会社</Link><Link aria-current={business === 'agriculture' ? 'page' : undefined} href="/shop/contact?business=agriculture">農作物</Link><Link href="/shop/contact?business=cosmetics">化粧品（専用サイト） →</Link></nav>}<Steps current={step} labels={['内容の入力', '内容の確認', '受付完了']}/>{step === 2 ? <div className="success-panel"><h2>お問い合わせを受け付けました。</h2><p>受付番号：{receipt}</p><p>このデモでは外部への送信は行っていません。管理画面で受付内容をご確認いただけます。</p><Link className="button" href={business === 'corporate' ? '/' : '/shop'}>トップへ戻る →</Link></div> : <form className="contact-form" onChange={e => { if (business === 'corporate') { const changed: EventTarget = e.target; if (!(changed instanceof HTMLInputElement || changed instanceof HTMLTextAreaElement)) return; const name = changed.name; setFieldErrors(previous => ({ ...previous, [name]: '' })); } }} onInvalidCapture={e => { if (business === 'corporate') { e.preventDefault(); const input: EventTarget = e.target; if (!(input instanceof HTMLInputElement || input instanceof HTMLTextAreaElement)) return; const messages: Record<string, string> = { name: 'お名前を入力してください。', email: input.validity.typeMismatch ? 'メールアドレスの形式をご確認ください。' : 'メールアドレスを入力してください。', subject: '件名を入力してください。', message: 'お問い合わせ内容を入力してください。', consent: '内容をご確認のうえ、同意にチェックしてください。' }; setFieldErrors(previous => ({ ...previous, [input.name]: messages[input.name] || '入力内容をご確認ください。' })); e.currentTarget.querySelector<HTMLInputElement>(':invalid')?.focus(); } }} onSubmit={e => { e.preventDefault(); if (step === 0) {
    setStep(1);
    return;
} action.run(() => gateway.createInquiry({ ...form, business, consent, idempotencyKey: key }), result => { setReceipt(result.id); setStep(2); clearForm(); }); }}>{step === 0 ? <><Field label="お名前"><input name="name" aria-invalid={!!fieldErrors.name} aria-describedby={fieldErrors.name ? "inquiry-name-error" : undefined} required autoComplete="name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/>{fieldErrors.name && <span id="inquiry-name-error" className="corporate-field-error">{fieldErrors.name}</span>}</Field><Field label="メールアドレス"><input name="email" aria-invalid={!!fieldErrors.email} aria-describedby={fieldErrors.email ? "inquiry-email-error" : undefined} required type="email" autoComplete="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/>{fieldErrors.email && <span id="inquiry-email-error" className="corporate-field-error">{fieldErrors.email}</span>}</Field>{business !== 'corporate' && <Field label="注文番号" optional><input value={form.orderId} onChange={e => setForm({ ...form, orderId: e.target.value })}/><small>ログイン中のご本人の注文のみ関連付けできます。</small></Field>}<Field label="件名"><input name="subject" aria-invalid={!!fieldErrors.subject} aria-describedby={fieldErrors.subject ? "inquiry-subject-error" : undefined} required value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })}/>{fieldErrors.subject && <span id="inquiry-subject-error" className="corporate-field-error">{fieldErrors.subject}</span>}</Field><Field label="お問い合わせ内容"><textarea name="message" aria-invalid={!!fieldErrors.message} aria-describedby={fieldErrors.message ? "inquiry-message-error" : undefined} required rows={7} value={form.message} onChange={e => setForm({ ...form, message: e.target.value })}/>{fieldErrors.message && <span id="inquiry-message-error" className="corporate-field-error">{fieldErrors.message}</span>}</Field><Consent checked={consent} onChange={setConsent} error={fieldErrors.consent}/></> : <dl className="information confirmation">{Object.entries(form).filter(([, v]) => v).map(([k, v]) => <div key={k}><dt>{{ name: 'お名前', email: 'メールアドレス', subject: '件名', message: 'お問い合わせ内容', orderId: '注文番号' }[k]}</dt><dd className="preserve">{v}</dd></div>)}</dl>}<ErrorBox error={action.error}/><div className="actions">{step === 1 && <button type="button" className="button secondary" onClick={() => setStep(0)}>内容を修正する</button>}<button className="button" disabled={action.busy}>{action.busy ? '送信中…' : step === 0 ? '入力内容を確認する' : action.error ? 'もう一度送信する' : 'この内容で送信する'} →</button></div></form>}<DemoNote /></div>; }
