import { useEffect, useState } from 'react';
import { siteBusiness } from './site';
import { useGateway, useAction, useResource, ErrorBox, Loading } from './GatewayContext';
import { Link, navigate, safeNext } from './router';
import { Heading, Crumbs, Field, Consent, Empty, DemoNote } from './Shared';
import { GatewayError, businessNames, orderLabels, paymentLabels, shippingLabels, yen, type MemberInput } from './domain';
const blank: MemberInput = { name: '', email: '', phone: '', address: '', nickname: '', age: '' };
export function MemberFields({ value, onChange }: {
    value: MemberInput;
    onChange: (v: MemberInput) => void;
}) { return <div className="form-grid">{(['name', 'email', 'phone', 'address', 'nickname'] as const).map(k => <Field key={k} label={{ name: '氏名', email: 'メールアドレス', phone: '電話番号', address: '住所', nickname: 'ニックネーム' }[k]}><input required type={k === 'email' ? 'email' : k === 'phone' ? 'tel' : 'text'} autoComplete={{ name: 'name', email: 'email', phone: 'tel', address: 'street-address', nickname: 'nickname' }[k]} value={value[k]} onChange={e => onChange({ ...value, [k]: e.target.value })}/></Field>)}<Field label="年代"><select required value={value.age} onChange={e => onChange({ ...value, age: e.target.value })}><option value="">選択してください</option>{['10代以下', '20代', '30代', '40代', '50代', '60代', '70代以上'].map(age => <option key={age}>{age}</option>)}</select></Field></div>; }
export function AuthPage({ mode, next, token }: {
    token?: string;
    mode: 'login' | 'register' | 'reset' | 'recovery';
    next: string | null;
}) { const { gateway } = useGateway(); const action = useAction(); const [input, setInput] = useState<MemberInput>(blank); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [consent, setConsent] = useState(false); const [done, setDone] = useState(false); const to = safeNext(next); const title = token ? '新しいパスワードの設定' : { login: '会員ログイン', register: '新規会員登録', reset: 'パスワードをお忘れの方', recovery: 'ログインIDをお忘れの方' }[mode]; const submit = () => { if (mode === 'login')
    action.run(() => gateway.login(input.email, password), () => navigate(to));
else if (mode === 'register')
    action.run(() => gateway.register({ ...input, password, referralCode: code, consent }), () => navigate(to));
else if (mode === 'reset' && token)
    action.run(() => gateway.confirmPasswordReset(input.email, token, password), () => { setDone(true); setPassword(''); });
else
    action.run(() => gateway.requestRecovery(input.email, mode === 'reset' ? 'password' : 'id'), () => setDone(true)); }; return <div className="container page narrow"><Crumbs items={[{ label: 'ショップ', href: '/shop' }, { label: title }]}/><Heading title={title} lead={mode === 'register' ? '化粧品・農作物の両サイトで使える共通会員です。ログインはサイトごとに行います。紹介コードはなくても登録できます。' : mode === 'login' ? 'ご登録のメールアドレスでログインしてください。' : mode === 'recovery' ? '連絡可能なメールアドレスを入力してください。登録メールを使えない場合は、ショップ窓口へご相談ください。' : '登録済みのメールアドレスを入力してください。'}/>{done ? <div className="success-panel"><h2>{token ? "パスワード再設定の確認が完了しました。" : "回復手続きを受け付けました。"}</h2><p>{token ? "ローカル共通会員のデモ用パスワードを変更しました。両サイトで新しいパスワードをご利用ください。" : "登録情報が確認できた場合にご案内する想定です。このデモではメールは送信されません。"}</p><Link href={`/shop/login?next=${encodeURIComponent(to)}`} className="button">ログインへ戻る →</Link></div> : <form className="auth-form" onSubmit={e => { e.preventDefault(); submit(); }}>{mode === 'register' ? <MemberFields value={input} onChange={setInput}/> : <Field label={mode === 'recovery' ? '連絡可能なメールアドレス' : 'メールアドレス'}><input type="email" autoComplete="email" required value={input.email} onChange={e => setInput({ ...input, email: e.target.value })}/></Field>}{(mode === 'login' || mode === 'register' || !!token) && <Field label="パスワード"><input type="password" required minLength={8} autoComplete={mode === 'login' && !token ? 'current-password' : 'new-password'} value={password} onChange={e => setPassword(e.target.value)}/><span className="caption">8文字以上のデモ用パスワードを入力してください。ローカル共通サービスへ送信し、照合用の値を保持します。</span></Field>}{mode === 'register' && <><Field label="紹介コード" optional><input value={code} onChange={e => setCode(e.target.value)} autoCapitalize="characters"/><span className="caption">化粧品の対象商品に適用されます。農作物は対象外です。</span></Field><Consent checked={consent} onChange={setConsent}/></>}<ErrorBox error={action.error}/>{action.error instanceof GatewayError && action.error.code === 'REFERRAL_INVALID' && <button type="button" className="button secondary full" onClick={() => { setCode(''); action.clear(); }}>紹介コードを使わずに登録へ戻る →</button>}<button className="button full" disabled={action.busy}>{action.busy ? '確認しています…' : mode === 'login' ? 'ログインする' : mode === 'register' ? '会員登録して続ける' : token ? '新しいパスワードを確定する' : '回復手続きを進める'} <span>→</span></button>{mode === 'login' && <p className="demo-note">確認用アカウント：demo@example.invalid<br />パスワード：demo-password</p>}</form>}<div className="auth-links">{token && <Link href="/shop/reset">再設定案内をもう一度申し込む →</Link>}{mode === 'login' ? <><Link href={`/shop/register?next=${encodeURIComponent(to)}`}>初めてご利用の方：新規会員登録 →</Link><Link href={`/shop/reset?next=${encodeURIComponent(to)}`}>パスワードをお忘れの方</Link><Link href={`/shop/recovery?next=${encodeURIComponent(to)}`}>ログインIDをお忘れの方</Link></> : <Link href={`/shop/login?next=${encodeURIComponent(to)}`}>ログイン画面へ戻る</Link>}<Link href="/shop/contact">ショップに問い合わせる →</Link></div><DemoNote /></div>; }
export function AccountPage() { const { gateway, member, revision } = useGateway(); const [tab, setTab] = useState<'orders' | 'profile'>('orders'); const business = siteBusiness; const r = useResource(() => member ? gateway.getOrders(business || undefined) : Promise.resolve([]), [member?.id, business, revision]); const action = useAction(); if (!member)
    return <div className="container page narrow"><Heading title="会員ページ" lead="ご注文の確認と登録情報の変更にはログインが必要です。"/><Link className="button" href="/shop/login?next=%2Fshop%2Faccount">ログインする →</Link><Link className="button secondary" href="/shop/register">新規会員登録 →</Link></div>; return <div className="container page"><Crumbs items={[{ label: 'ショップ', href: '/shop' }, { label: '会員ページ' }]}/><div className="section-top"><Heading title="会員ページ" lead={`${member.nickname} さん、こんにちは。`}/><button className="text-button" onClick={() => action.run(() => gateway.logout(), () => navigate('/shop'))}>ログアウト</button></div><nav className="tabs" aria-label="会員メニュー"><button aria-pressed={tab === 'orders'} onClick={() => setTab('orders')}>注文履歴</button><button aria-pressed={tab === 'profile'} onClick={() => setTab('profile')}>登録情報</button></nav>{tab === 'profile' ? <ProfileForm /> : <><p className="notice">このサイトでは{businessNames[business]}のご注文を表示します。登録情報は両サイト共通です。</p>{r.loading ? <Loading /> : r.error ? <ErrorBox error={r.error} retry={r.retry}/> : !r.data?.length ? <Empty title="まだご注文はありません" href="/shop"/> : <div className="order-list">{r.data.map(o => <article key={o.id}><div className="section-top"><div><span className="tag">{businessNames[o.business]}</span><h2>{o.id}</h2><small>{o.createdAt.slice(0, 10)}</small></div><strong>{yen(o.total)}</strong></div><p>{o.items.map(l => `${l.name} × ${l.quantity}`).join(' / ')}</p><div className="order-statuses"><span>{orderLabels[o.status]}</span><span>{paymentLabels[o.payment.status]}</span><span>{shippingLabels[o.shipping.status]}</span></div><p className="caption">{o.shipping.carrier || '配送会社未確定'} / {o.shipping.tracking || '追跡情報は発送後に表示'}</p><Link className="line-link" href={`/shop/orders/${o.id}`}>注文内容・支払いを確認する <span>→</span></Link></article>)}</div>}</>}<ErrorBox error={action.error}/><DemoNote /></div>; }
function ProfileForm() { const { gateway, member } = useGateway(); const [value, setValue] = useState<MemberInput>(member!); const [dirty, setDirty] = useState(false); useEffect(() => { if (!dirty && member) setValue(member); }, [member, dirty]); const [done, setDone] = useState(false); const action = useAction(); return <form className="profile-form" onSubmit={e => { e.preventDefault(); action.run(() => gateway.updateMember(value), () => { setDone(true); setDirty(false); }); }}><h2>登録情報の変更</h2><MemberFields value={value} onChange={v => { setValue(v); setDirty(true); setDone(false); }}/><p>紹介コード：{member?.referralCode || '登録なし'}<br /><small>紹介者は登録時の1名です。変更の相談はお問い合わせ窓口へ。</small></p><ErrorBox error={action.error}/>{done && <p className="success" role="status">登録情報を更新しました。</p>}<button className="button" disabled={action.busy}>変更を保存する →</button></form>; }
